# About the author {.unnumbered}

Rohan Alexander is an assistant professor at the University of Toronto in Information and Statistical Sciences. He is also the assistant director of CANSSI Ontario, a senior fellow at Massey College, a faculty affiliate at the Schwartz Reisman Institute for Technology and Society, and a co-lead of the Data Sciences Institute Thematic Program in Reproducibility. He holds a PhD in Economics from the Australian National University where he was supervised by John Tang (chair), Martine Mariotti, Tim Hatton, and Zach Ward.

He is interested in using statistical models to try to understand the world. And particularly how we get the data that go into those models; whose data are systematically missing; how we clean, prepare, and tidy data before they are modelled; the effects of all this on the implications of our models; and how we can reproducibly share the totality of this process. He tries to develop students that are skilled not only in using statistical methods across various disciplines, but also appreciate their limitations, and think deeply about the broader contexts of their work. 

He enjoys teaching and aims to help students from a wide range of backgrounds learn how to use data to tell convincing stories. He teaches in both the Faculty of Information and the Department of Statistical Sciences at both undergraduate and graduate levels. He is a RStudio Certified Tidyverse Trainer.

He is married to Monica Alexander and they have two children. He probably spends too much money on books, and certainly too much time at libraries. If you have any book recommendations of your own, then he'd love to hear them.
