---
engine: knitr
---

# Datasets {#sec-datasets}

In general, it is better to stay away from datasets on Kaggle, the UCI Machine Learning Repository, and other commonly used options. From a data science perspective, using a dataset as it is available from such a source means that almost all the important decisions have been already made, and are potentially undocumented. And from a career perspective, it does not set your portfolio apart because everyone else just uses these datasets. Some alternatives include:

- [Alex Cookson's datasets](https://github.com/tacookson/data).
- @andrews2012data provides a variety of datasets, which are available [here](https://www.york.ac.uk/depts/maths/histstat/pml1/r/andrews.htm).
- [*APIs for social scientists*](https://bookdown.org/paul/apis_for_social_scientists/) provides a variety of APIs that could be used to gather data.
- BuzzFeed News provides [access](https://github.com/BuzzFeedNews/nics-firearm-background-checks) to many datasets underpinning their articles. 
- [The Data And Story Library](https://dasl.datadescription.com) provides access to hundreds of datasets.
- Duolingo [provides](https://research.duolingo.com) access to datasets that underpin its research papers.
- The Economist proves [access](https://github.com/orgs/TheEconomist/repositories) to many datasets underpinning their articles.
- Federal Reserve Economic Data (FRED) [provides](https://fred.stlouisfed.org) economic data.
- FiveThirtyEight proves [access](https://github.com/fivethirtyeight/data) to many datasets underpinning their articles.
- [Historical Statistics](https://www.historicalstatistics.org/) provides links to historical statistics.
- [Human Mortality Database](https://www.mortality.org) provides detailed mortality and population data for a variety of countries.
- [IPCC Data Distribution Centre](https://www.ipcc-data.org).
- The Irish Social Science Data Archive has a wide variety of datasets [available](https://www.ucd.ie/issda/data/).
- The J-PAL (Abdul Latif Jameel Poverty Action Lab) [catalog of administrative data](https://www.povertyactionlab.org/catalog-administrative-data-sets).
- The Markup's [Show Your Work](https://themarkup.org/series/show-your-work) series often include links to GitHub repos with the data that underpin the article.
- The Massachusetts Water Resources Authority makes its Wastewater COVID-19 Tracking data available [here](https://www.mwra.com/biobot/biobotdata.htm), with the raw data available in a PDF that could be parsed.
- [Microsoft Research Open Data](https://msropendata.com) has a large number of datasets across computer science, social science, information science, and other categories.
- The Museum of Modern Art (MoMA) makes datasets about their [collection](https://github.com/MuseumofModernArt/collection) and [exhibitions](https://github.com/MuseumofModernArt/exhibitions) available.
- NASA's [Planetary Data System](https://pds.nasa.gov).
- The OECD [provides](https://data.oecd.org) economic data.
- The Prison Policy Initiative provides many [datasets](https://www.prisonpolicy.org/data/) about US prisons and jails.
- The Rijksmuseum [provides](https://data.rijksmuseum.nl) a variety of data about their collections.
- Tom Cardoso's [Bias behind bars](https://www.theglobeandmail.com/canada/article-investigation-racial-bias-in-canadian-prison-risk-assessments/) provides data about Black and Indigenous inmates in Canada.
- The Washington Post proves [access](https://github.com/washingtonpost) to many datasets underpinning their articles. Especially of interest may be [congress slaveowners](https://github.com/washingtonpost/data-congress-slaveowners), [fatal force shooting](https://github.com/washingtonpost/data-police-shootings), and [school shootings](https://github.com/washingtonpost/data-school-shootings).
- The [Wordbank database](http://wordbank.stanford.edu) is an open database of children's vocabulary growth. Access is additionally available using `wordbankr` [@wordbankr], and Alison Presmanes Hill provides useful [background](https://apreshill.github.io/data-vis-labs-2018/03-colors.html) and [cleaning code](https://apreshill.github.io/data-vis-labs-2018/03a-meow-cleaning.html).
- The World Bank provides an extensive range of [global development data](https://data.worldbank.org) and a [Microdata Library](https://microdata.worldbank.org/index.php/home/).
- Yale's International Center for Finance datasets: [Historical Financial Research Data](https://som.yale.edu/centers/international-center-for-finance/data/historical-financial-research-data), and [Stock Market Confidence Indices](https://som.yale.edu/centers/international-center-for-finance/data/stock-market-confidence-indices).



