---
engine: knitr
---

# Activities {#sec-activities}

There are various ways that I have found to use this book in classes. There does not seem to be one best way, but it seems to depend on enthusiasm and size of the group. If they are able to commit to reading the chapter before the lecture, then I have found using class for group-based projects and discussion is nice. Each week create small groups, each of two to four students (create new groups every week to give students a chance to work with new people), and then have them work through most exercises, first by themselves, then compare with their group, and finally share selected answers with the class. 

**Chapter 1---Telling stories with data**

- Write a one-paragraph response to: "What is data science?". Strong answers would include references and draw on your own experience.
- Take a photo of the class, then display the photo. Ask the students in their groups to write three aspects about who the photo shows (faces, class composition, etc), and three aspects about what the photo does not (context, thoughts, emotions, motivations, students who are not present, etc). Discuss how this relates to data science.
- Discuss the ten elements of telling convincing stories with data. Then have the students talk about one that they are particularly experienced with, and another that they are less experienced with.
- How you would go about answering the following question: "How long is your hair?"

**Chapter 2---Drinking from a fire hose**

- Call on students to explain each of `mutate()`, `select()`, `filter()`, `arrange()`, `summarize()`, and then code an example of their use.
- Explain what class is, with an example.
- Simulate 100 draws from the uniform distribution with mean 5 and standard deviation 2. Write one test for this dataset.
- Simulate 50 draws from the Poisson distribution with lambda 10. Write two tests for this dataset.
- Gather some data on Marriage Licence Statistics in Toronto using Open Data Toronto, then clean and graph it (hint: consider `separate()` and them `lubridate::ymd()` for the dates).

**Chapter 3---Reproducible workflows**

- Make a new R Project with an appropriate file structure.
- Use Quarto to make a PDF with a title, author, and an abstract.
- Add three sections and some code that produces the mean bill length, by species, for `palmerpenguins::penguins` (with the code itself hidden).
- Add a citation of R and `palmerpenguins` and also add a graph of body mass, by sex.
- Add a paragraph of text about the graph and a cross-reference. Also add a table about the number of species, by year.
- Make a GitHub repo and push all this to it. 
- Add someone from another group to it. Ask them to fork it, make a small change, and then make a pull request.

**Chapter 4---Writing research**

- *Paper review:* Please read @Gerring2012 and write a review of at least two pages.
- Make a plan, based on @king2006publication, for how you will write a meaningful paper by the end of this class. (For PhD students: Detail three journals/conferences, in order, that you will submit it to, and why the paper would be a good fit at each.)

**Chapter 5---Static communication**



**Chapter 6---Farm data**

- *Paper review:* Please read @Bradley2021 and write a review of at least two pages.

**Chapter 7---Gather data**

- *Paper review:* Please read @Kish1959

**Chapter 8---Hunt data**

- *Paper review:* With reference to @Hammond2022, please discuss experimental design, informed consent and equipoise. Please write at least two pages.

**Chapter 9---Clean and prepare**

**Chapter 10---Store and share**

**Chapter 11---Exploratory data analysis**

**Chapter 12---Linear models**

- Please use the data underpinning @cohn2016, available [here](https://github.com/TheUpshot/2016-upshot-siena-polls/), to build three different models and compare the results.

**Chapter 13---Generalized linear models**

**Chapter 14---Causality from observational data**

**Chapter 15---Multilevel regression with post-stratification**

- *Paper review:* Please read @wang2015forecasting and write a review of at least two pages.

**Chapter 16---Text as data**

**Appendix A---R essentials**

