<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.486">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Telling Stories with Data - 10&nbsp; Hunt data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11-clean_and_prepare.html" rel="next">
<link href="./09-gather.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hunt data</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Telling Stories with Data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/RohanAlexander/telling_stories/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-author.html" class="sidebar-item-text sidebar-link">About the author</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Foundations</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Telling stories with data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-drinking_from_a_fire_hose.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Drinking from a fire hose</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-r_essentials.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R essentials</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reproducible workflows</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Communication</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-on_writing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">On writing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-static_communication.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Static communication</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-interactive_communication.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Interactive communication</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Acquisition</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-farm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Farm data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-gather.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Gather data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-hunt.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hunt data</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Preparation</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-clean_and_prepare.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Clean and prepare</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-store_and_share.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Store and share</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Modelling</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-eda.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Exploratory data analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-ijalm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">It’s Just A Linear Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-causality_from_obs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Causality from observational data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-mrp.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Multilevel regression with post-stratification</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-text.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Text as data</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Enrichment</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-deploy.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Deploying models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-efficiency.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Efficiency</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-concluding.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Concluding remarks</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">Appendices</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-assessment.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Papers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-datasets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Datasets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98-cocktails.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Cocktails</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#experiments-and-randomized-controlled-trials" id="toc-experiments-and-randomized-controlled-trials" class="nav-link active" data-scroll-target="#experiments-and-randomized-controlled-trials"> <span class="header-section-number">10.1</span> Experiments and randomized controlled trials</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"> <span class="header-section-number">10.1.1</span> Introduction</a></li>
  <li><a href="#motivation-and-notation" id="toc-motivation-and-notation" class="nav-link" data-scroll-target="#motivation-and-notation"> <span class="header-section-number">10.1.2</span> Motivation and notation</a></li>
  <li><a href="#randomization" id="toc-randomization" class="nav-link" data-scroll-target="#randomization"> <span class="header-section-number">10.1.3</span> Randomization</a></li>
  <li><a href="#treatment-and-control" id="toc-treatment-and-control" class="nav-link" data-scroll-target="#treatment-and-control"> <span class="header-section-number">10.1.4</span> Treatment and control</a></li>
  <li><a href="#fishers-tea-party" id="toc-fishers-tea-party" class="nav-link" data-scroll-target="#fishers-tea-party"> <span class="header-section-number">10.1.5</span> Fisher’s tea party</a></li>
  <li><a href="#informed-consent-and-the-need-for-an-experiment" id="toc-informed-consent-and-the-need-for-an-experiment" class="nav-link" data-scroll-target="#informed-consent-and-the-need-for-an-experiment"> <span class="header-section-number">10.1.6</span> Informed consent and the need for an experiment</a></li>
  <li><a href="#case-study-the-oregon-health-insurance-experiment" id="toc-case-study-the-oregon-health-insurance-experiment" class="nav-link" data-scroll-target="#case-study-the-oregon-health-insurance-experiment"> <span class="header-section-number">10.1.7</span> Case study: The Oregon Health Insurance Experiment</a></li>
  </ul></li>
  <li><a href="#ab-testing" id="toc-ab-testing" class="nav-link" data-scroll-target="#ab-testing"> <span class="header-section-number">10.2</span> A/B testing</a>
  <ul class="collapse">
  <li><a href="#case-study-upworthy" id="toc-case-study-upworthy" class="nav-link" data-scroll-target="#case-study-upworthy"> <span class="header-section-number">10.2.1</span> Case study: Upworthy</a></li>
  </ul></li>
  <li><a href="#implementing-surveys" id="toc-implementing-surveys" class="nav-link" data-scroll-target="#implementing-surveys"> <span class="header-section-number">10.3</span> Implementing surveys</a></li>
  <li><a href="#exercises-and-tutorial" id="toc-exercises-and-tutorial" class="nav-link" data-scroll-target="#exercises-and-tutorial"> <span class="header-section-number">10.4</span> Exercises and tutorial</a>
  <ul class="collapse">
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"> <span class="header-section-number">10.4.1</span> Exercises</a></li>
  <li><a href="#tutorial" id="toc-tutorial" class="nav-link" data-scroll-target="#tutorial"> <span class="header-section-number">10.4.2</span> Tutorial</a></li>
  <li><a href="#paper" id="toc-paper" class="nav-link" data-scroll-target="#paper"> <span class="header-section-number">10.4.3</span> Paper</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/RohanAlexander/telling_stories/edit/main/10-hunt.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-hunt-data" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hunt data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p><strong>Required material</strong></p>
<ul>
<li>Read <em>Big tech is testing you</em>, <span class="citation" data-cites="fry2020big">(<a href="references.html#ref-fry2020big" role="doc-biblioref">Fry 2020</a>)</span>.</li>
<li>Read <em>Inventing the randomized double-blind trial: the Nuremberg salt test of 1835</em>, <span class="citation" data-cites="stolberg2006inventing">(<a href="references.html#ref-stolberg2006inventing" role="doc-biblioref">Stolberg 2006</a>)</span>.</li>
<li>Read <em>Impact evaluation in practice</em>, Chapters 3 and 4, <span class="citation" data-cites="gertler2016impact">(<a href="references.html#ref-gertler2016impact" role="doc-biblioref">Gertler et al. 2016</a>)</span>.</li>
<li>Read <em>Statistics and causal inference</em>, Parts 1-3, <span class="citation" data-cites="holland1986statistics">(<a href="references.html#ref-holland1986statistics" role="doc-biblioref">Holland 1986</a>)</span>.</li>
</ul>
<!-- **Required reading** -->
<!-- - Banerjee, Abhijit Vinayak, 2020, 'Field Experiments and the Practice of Economics', *American Economic Review*, Vol. 110, No. 7, pp. 1937-1951. -->
<!-- - Berry, Donald, 1989, 'Comment: Ethics and ECMO', *Statistical Science*, Vol 4, No 4, pp. 306-310. -->
<!-- - Duflo, Esther, 2020, 'Field Experiments and the Practice of Policy', *American Economic Review*, Vol. 110, No. 7, pp. 1952-1973 (or watch the speech detailed below). -->
<!-- - Fisher, Ronald, 1935, *The Design of Experiments*, pp. 20-29, https://archive.org/details/in.ernet.dli.2015.502684/page/n33/mode/2up. -->
<!-- - Gertler, Paul, Sebastian Martinez, Patrick Premand, Laura Rawlings, and Christel Vermeersch, *Impact Evaluation in Practice*, Chapters 3 and 4, https://www.worldbank.org/en/programs/sief-trust-fund/publication/impact-evaluation-in-practice. -->
<!-- - Hill, Austin Bradford, 1965, 'The Environment and Disease: Association or Causation?', *Proceedings of the Royal Society of Medicine*, 58, 5, 295-300. -->
<!-- - Kohavi, Ron and Stefan Thomke, 2017, 'The Surprising Power of Online Experiments', *Harvard Business Review*, September-October, https://hbr.org/2017/09/the-surprising-power-of-online-experiments. -->
<!-- - Kohavi, Ron, Diane Tang, and Ya Xu, 2020, *Trustworthy Online Controlled Experiments: A Practical Guide to A/B Testing*, Cambridge University Press. (This sounds like a lot, but it is a light book - it is more about providing examples of issues to think about.) (Freely available through the U of T library.) -->
<!-- - Taylor, Sean, Dean Eckles, 2017, 'Randomized experiments to detect and estimate social influence in networks', *arXiv*, https://arxiv.org/abs/1709.09636v1. -->
<!-- - Ware, James H., 1989, 'Investigating Therapies of Potentially Great Benefit: ECMO', *Statistical Science*, Vol 4, No 4, pp. 298-306. -->
<!-- **Required viewing** -->
<!-- - Ge, Kathy, 2021, 'Experimentation and product design at Uber', *Toronto Data Workshop*, 4 February, https://youtu.be/UYzXElJTovg.  -->
<!-- - Xu, Ya, 2020, 'Causal inference challenges in industry, a perspective from experiences at LinkedIn', *Online Causal Inference Seminar*, 16 July, https://youtu.be/OoKsLAvyIYA. -->
<!-- **Recommended reading** -->
<!-- - Angrist, Joshua D., and Jörn-Steffen Pischke, 2008, *Mostly harmless econometrics: An empiricist's companion*, Princeton University Press, Chapter 2. -->
<!-- - Banerjee, Abhijit Vinayak, Esther Duflo, Rachel Glennerster, and Dhruva Kothari, 2010, 'Improving immunisation coverage in rural India: clustered randomized controlled evaluation of immunisation campaigns with and without incentives', *BMJ*, 340, c2220. -->
<!-- - Beaumont, Jean-François, 2020, 'Are probability surveys bound to disappear for the production of official statistics?', *Survey Methodology*, 46 (1), Statistics Canada, Catalogue No. 12-001-X. -->
<!-- - Christian, Brian, 2012, 'The A/B Test: Inside the Technology That's Changing the Rules of Business', *Wired*, 25 April, https://www.wired.com/2012/04/ff-abtesting/. -->
<!-- - Dablander, Fabian, 2020, "An Introduction to Causal Inference", *PsyArXiv*, 13 February, doi:10.31234/osf.io/b3fkw, https://psyarxiv.com/b3fkw. -->
<!-- - Deaton, Angus, 2010, 'Instruments, Randomization, and Learning about Development', *Journal of Economic Literature*, vol. 48, no. 2, pp. 424-455. -->
<!-- - Duflo, Esther, Rachel Glennerster, and Michael Kremer, 2007, 'Using Randomization In Development Economics Research: A Toolkit', https://economics.mit.edu/files/806. -->
<!-- - Gordon, Brett R., Florian Zettelmeyer, Neha Bhargava, and Dan Chapsky, 2019, 'A Comparison of Approaches to Advertising Measurement: Evidence from Big Field Experiments at Facebook', *Marketing Science*, Vol. 38, No. 2, March–April, pp. 193–225. -->
<!-- - Groves, Robert M., 2011, 'Three Eras of Survey Research', *Public Opinion Quarterly*, 75 (5), pp. 861–871, https://doi.org/10.1093/poq/nfr057. -->
<!-- - Hillygus, D. Sunshine, 2011, 'The evolution of election polling in the United States', *Public Opinion Quarterly*, 75 (5), pp. 962-981. -->
<!-- - Imai, Kosuke, 2017, *Quantitative Social Science: An Introduction*, Princeton University Press, Ch 2.3, 2.4, 4.3. -->
<!-- - Jeffries, Adrianne, Leon Yin, and Surya Mattu, 2020, 'Swinging the Vote?', *The Markup*, 26 February, https://themarkup.org/google-the-giant/2020/02/26/wheres-my-email. -->
<!-- - Kohavi, Ron, Alex Deng, Brian Frasca, Roger Longbotham, Toby Walker, and Ya Xu. 2012. Trustworthy online controlled experiments: five puzzling outcomes explained. In Proceedings of the 18th ACM SIGKDD international conference on Knowledge discovery and data mining (KDD '12). Association for Computing Machinery, New York, NY, USA, 786–794. DOI:https://doi.org/10.1145/2339530.2339653 -->
<!-- - Landesberg, Eddie, Molly Davies, and Stephanie Yee, 2019, 'Want to make good business decisions? Learn causality', *MultiThreaded, Stitchfix blog*, 19 December, https://multithreaded.stitchfix.com/blog/2019/12/19/good-marketing-decisions/. -->
<!-- - Levay, Kevin E., Jeremy Freese, and James N. Druckman, 2016, 'The demographic and political composition of Mechanical Turk samples', *Sage Open*, 6 (1), 2158244016636433. -->
<!-- - Lewis, Randall A., and David H. Reiley, 2014 'Online ads and offline sales: Measuring the effects of retail advertising via a controlled experiment on Yahoo!', *Quantitative Marketing and Economics*, Vol 12, pp. 235–266.  -->
<!-- - Mullinix, Kevin J., Leeper, Thomas J., Druckman, James N. and Freese, Jeremy, 2015, 'The generalizability of survey experiments', *Journal of Experimental Political Science*, 2 (2), pp. 109-138. -->
<!-- - Novak, Greg, Sven Schmit, and Dave Spiegel, 2020, Experimentation with resource constraints, 18 November, StitchFix Blog, https://multithreaded.stitchfix.com/blog/2020/11/18/virtual-warehouse/. -->
<!-- - Prepared for the AAPOR Executive Council by a Task Force operating under the auspices of the AAPOR Standards Committee, with members including:, Reg Baker, Stephen J. Blumberg, J. Michael Brick, Mick P. Couper, Melanie Courtright, J. Michael Dennis, Don Dillman, Martin R. Frankel, Philip Garland, Robert M. Groves, Courtney Kennedy, Jon Krosnick, Paul J. Lavrakas, Sunghee Lee, Michael Link, Linda Piekarski, Kumar Rao, Randall K. Thomas, Dan Zahs, 2010, 'Research Synthesis: AAPOR Report on Online Panels', *Public Opinion Quarterly*, 74 (4), pp. 711–781, https://doi.org/10.1093/poq/nfq048.  -->
<!-- - Ryan, A. C., A. R. MacKenzie, S. Watkins, and R. Timmis, 2012, 'World War II contrails: a case study of aviation‐induced cloudiness', *International journal of climatology*, 32, no. 11, pp. 1745-1753. -->
<!-- - Said, Chris, 2020, 'Optimizing sample sizes in A/B testing, Part I: General summary', 10 January, https://chris-said.io/2020/01/10/optimizing-sample-sizes-in-ab-testing-part-I/. (See also parts 2 and 3). -->
<!-- - Stolberg, Michael, 2006, 'Inventing the randomized double-blind trial: the Nuremberg salt test of 1835', *Journal of the Royal Society of Medicine*, 99, no. 12, pp. 642-643. -->
<!-- - Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel, 2019, popular science background, https://www.nobelprize.org/uploads/2019/10/popular-economicsciencesprize2019-2.pdf. -->
<!-- - Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel, 2019, scientific background, https://www.nobelprize.org/uploads/2019/10/advanced-economicsciencesprize2019.pdf. -->
<!-- - Taddy, Matt, 2019, *Business Data Science*, Chapter 5. -->
<!-- - Urban, Steve, Rangarajan Sreenivasan, and Vineet Kannan, 2016, 'it is All A/Bout Testing: The Netflix Experimentation Platform', *Netflix Technology Blog*, 29 April, https://netflixtechblog.com/its-all-a-bout-testing-the-netflix-experimentation-platform-4e1ca458c15. -->
<!-- - VWO, 'A/B Testing Guide', https://vwo.com/ab-testing/. -->
<!-- - Yeager, David S., Jon A. Krosnick, LinChiat Chang, Harold S. Javitz, Matthew S. Levendusky, Alberto Simpser, Rui Wang, 2011, 'Comparing the Accuracy of RDD Telephone Surveys and Internet Surveys Conducted with Probability and Non-Probability Samples', *Public Opinion Quarterly*, 75 (4), pp. 709–747, https://doi.org/10.1093/poq/nfr020. -->
<!-- - Yin, Xuan and Ercan Yildiz, 2020, 'The Causal Analysis of Cannibalization in Online Products', *Code as Craft, Etsy blog*, 24 February, https://codeascraft.com/2020/02/24/the-causal-analysis-of-cannibalization-in-online-products/. -->
<!-- **Recommended listening** -->
<!-- - Galef, Julia, 2020, 'Episode 246: Deaths of despair / Effective altruism (Angus Deaton)', *Rationally Speaking*, from 35:30 through to the end, available at: http://rationallyspeakingpodcast.org/show/episode-246-deaths-of-despair-effective-altruism-angus-deato.html. -->
<!-- **Recommended viewing** -->
<!-- - Duflo, Esther, 2020, 'Inteview with Esther Duflo', 12 October, *Online Causal Inference Seminar*, https://youtu.be/WWW9q3oMYxU.  -->
<!-- - Duflo, Esther, 2019, 'Nobel Prize Lecture', 8 December 2019, Stockholm: https://www.nobelprize.org/prizes/economic-sciences/2019/duflo/lecture/. -->
<!-- - Tipton, Elizabeth, 2020, 'Will this Intervention Work in this Population? Designing Randomized Trials for Generalization', *Online Causal Inference Seminar*, 14 April, https://youtu.be/HYP32wzEZMA. -->
<p><strong>Key concepts and skills</strong></p>
<ul>
<li>Treatment and control groups.</li>
<li>Internal and external validity.</li>
<li>Average treatment effect.</li>
<li>Generating simulated datasets.</li>
<li>Informed consent and establishing the need for an experiment.</li>
<li>A/B testing</li>
<li>Putting together surveys with Google Forms</li>
</ul>
<p><strong>Key packages and functions</strong></p>
<ul>
<li><p><code>tidyverse</code> <span class="citation" data-cites="tidyverse">(<a href="references.html#ref-tidyverse" role="doc-biblioref">Wickham et al. 2019</a>)</span></p></li>
<li><p><code>count()</code></p></li>
<li><p><code>filter()</code></p></li>
<li><p><code>ggplot()</code></p></li>
<li><p><code>group_by()</code></p></li>
<li><p><code>head()</code></p></li>
<li><p><code>here()</code></p></li>
<li><p><code>if_else()</code></p></li>
<li><p><code>left_join()</code></p></li>
<li><p><code>length()</code></p></li>
<li><p><code>mean()</code></p></li>
<li><p><code>mutate()</code></p></li>
<li><p><code>names()</code></p></li>
<li><p><code>nrow()</code></p></li>
<li><p><code>pivot_wider()</code></p></li>
<li><p><code>read_csv()</code></p></li>
<li><p><code>ref()</code></p></li>
<li><p><code>rename()</code></p></li>
<li><p><code>rnorm()</code></p></li>
<li><p><code>rowwise()</code></p></li>
<li><p><code>sample()</code></p></li>
<li><p><code>scale_fill_brewer()</code></p></li>
<li><p><code>seed()</code></p></li>
<li><p><code>select()</code></p></li>
<li><p><code>str_detect()</code></p></li>
<li><p><code>sum()</code></p></li>
<li><p><code>summarize()</code></p></li>
<li><p><code>test()</code></p></li>
<li><p><code>theme_classic()</code></p></li>
<li><p><code>theme_minimal()</code></p></li>
<li><p><code>tibble()</code></p></li>
<li><p><code>ungroup()</code></p></li>
</ul>
<section id="experiments-and-randomized-controlled-trials" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="experiments-and-randomized-controlled-trials"><span class="header-section-number">10.1</span> Experiments and randomized controlled trials</h2>
<section id="introduction" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">10.1.1</span> Introduction</h3>
<p>Ronald Fisher, the twentieth century statistician, and Francis Galton, the nineteenth century statistician, are the intellectual grandfathers of much of the work that we cover in this chapter. In some cases it is directly their work, in other cases it is work that built on their contributions. Both men believed in eugenics, amongst other things that are generally reprehensible. In the same way that art history must acknowledge, say Caravaggio as a murderer, while also considering his work and influence, so to must statistics and the data sciences more generally concern themselves with this past, at the same time as we try to build a better future.</p>
<p>This chapter is about experiments. This is a situation in which we can explicitly control and vary that which we are interested in. The advantage of this is that identification should be clear. There is a treatment group that is subject to that which we are interested in, and a control group that is not. These are randomly split before treatment. And so, if they end up different then it must be because of the treatment. Unfortunately, life is rarely so smooth. Arguing about how similar the treatment and control groups were tends to carry on indefinitely. Our ability to speak to whether we have measured the effect of the treatment, affects our ability to speak to what effect that treatment could have.</p>
<!-- It is also important to note that the statistics of this were designed in agricultural settings 'does fertilizer work?', etc. In those settings one can more easily divide a field into 'treated' and 'non-treated', and the magnitude of the effect tends to be large. In general, these same statistical approaches are still used today (especially in the social sciences) but often inappropriately. If you hear someone talking about 'having enough power' and similar phrases, then it is *not* necessarily that they are *not* right, but it usually pays to take a step back and really think about what is being done and whether they really know what they are doing. -->
<p>In this chapter we cover experiments, especially constructing treatment and control groups, and appropriately considering their results. We discuss some aspects of ethical behaviour in experiments through reference to the abhorrent Tuskegee Syphilis Study and ECMO. And we go through the Oregon Health Insurance Experiment as a case study. We then turn to A/B testing, which is extensively used in industry, and consider a case study based on Upworthy data. Finally, we go through actually implementing a survey using Google Forms. <!-- Finally, we compare automated approaches such as obtaining data from sensors, with the notoriously slow, but crucial approach of making Freedom of Information requests. --></p>
</section>
<section id="motivation-and-notation" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="motivation-and-notation"><span class="header-section-number">10.1.2</span> Motivation and notation</h3>
<p>Professional sports are a big deal in North America. Consider the situation of someone who moves to San Francisco in 2014, such that as soon as they moved the Giants win the World Series and the Golden State Warriors begin a historic streak of World Championships. They move to Chicago, and immediately the Cubs win the World Series for the first time in a hundred years. They move to Massachusetts, where the Patriots win the Super Bowl again, and again, and again. And finally, they move to Toronto, where the Raptors immediately win the World Championship. Should a city pay them to move, or could municipal funds be better spent elsewhere?</p>
<p>One way to get at the answer would be to run an experiment. Make a list of the North American cities with major sports teams, and then roll a dice and send them to live there for a year. With enough lifetimes, we could work it out. The fundamental issue is that we cannot both live in a city and not live in a city. This is the fundamental problem of causal inference: a person cannot be both treated and untreated. Experiments and randomized controlled trials are circumstances in which we try to randomly allocate some treatment, to have a belief that everything else was the same (or at least ignorable). The framework that we use to formalize the situation is the Neyman-Rubin model <span class="citation" data-cites="holland1986statistics">(<a href="references.html#ref-holland1986statistics" role="doc-biblioref">Holland 1986</a>)</span>.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Shoulders of giants
</div>
</div>
<div class="callout-body-container callout-body">
<p>Donald B. Rubin</p>
</div>
</div>
<p>A treatment, <span class="math inline">\(t\)</span>, will often be a binary variable that is either 0 or 1. It is 0 if the person, <span class="math inline">\(i\)</span>, is not treated, which is to say they are in the control group, and 1 if they are treated. We will typically have some outcome, <span class="math inline">\(Y_i\)</span>, of interest for that person, and that could be binary, multinomial, or continuous. For instance, it could be vote choice, in which case we could measure whether the person is: ‘Conservative’ or ‘Not Conservative’; which party they support, say: ‘Conservative’, ‘Liberal’, ‘Democratic’, ‘Green’; or maybe a probability of support.</p>
<p>A treatment is causal if <span class="math inline">\((Y_i|t=0) \neq (Y_i|t=1)\)</span>. That is to say, that the outcome for person <span class="math inline">\(i\)</span>, given they were not treated, is different to their outcome given they were treated. If we could both treat and control the one individual at the one time, then we would know that it was only the treatment that had caused any change in outcome, as there is no other factor that could explain it. But the fundamental problem of causal inference is that we cannot both treat and control the one individual at the one time. So when we want to know the effect of the treatment, we need to compare it with a counterfactual. The counterfactual is what would have happened if the individual were not treated. As it turns out, this means one way to think of causal inference is as a missing data problem, where we are missing the counterfactual.</p>
<p>As we cannot compared treatment and control in one individual, we instead compare the average of two groups—all those treated and all those not. We are looking to estimate the counterfactual at a group level because of the impossibility of doing it at an individual level. Making this trade-off allows us to move forward but comes at the cost of certainty. We must instead rely on randomization, probabilities, and expectations.</p>
<p>We usually consider a default of there being no effect and we look for evidence that would cause us to change our mind. As we are interested in what is happening in groups, we turn to expectations, and notions of probability to express ourselves. Hence, we will make claims that talk, on average. Maybe wearing fun socks really does make you have a lucky day, but on average, across the group, it is probably not the case.</p>
<p>It is worth pointing out that we do not just have to be interested in the average effect. We may consider the median, or variance, or whatever. Nonetheless, if we were interested in the average effect, then one way to proceed would be to:</p>
<ol type="1">
<li>divide the dataset into two—treated and not treated—and have a binary effect column;</li>
<li>sum the column, then divide it by the length of the column; and</li>
<li>then look at the ratio.</li>
</ol>
<p>This is an estimator, touched on in Chapter @ref(on-writing), which is a way of putting together a guess of something of interest. The estimand is the thing of interest, in this case the average effect, and the estimate is whatever our guess turns out to be. We can simulate data to illustrate the situation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>treatment_control <span class="ot">&lt;-</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">binary_effect =</span> <span class="fu">sample</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>treatment_control</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 1
   binary_effect
           &lt;dbl&gt;
 1             0
 2             1
 3             1
 4             0
 5             0
 6             0
 7             0
 8             0
 9             1
10             1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>estimate <span class="ot">&lt;-</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(treatment_control<span class="sc">$</span>binary_effect) <span class="sc">/</span> <span class="fu">length</span>(treatment_control<span class="sc">$</span>binary_effect)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4</code></pre>
</div>
</div>
<p>More broadly, to tell causal stories we need to bring together both theory and a detailed knowledge of what we are interested in <span class="citation" data-cites="Cunningham2021">(<a href="references.html#ref-Cunningham2021" role="doc-biblioref">Cunningham 2021, 4</a>)</span>. In Chapter @ref(gather-data) we discussed gathering data that we observed about the world. In this chapter we are going to be more active about turning the world into the data that we need. As the researcher we will decide what to measure and how, and we will need to define what we are interested in and what we are not. We will be active participants in the data generating process. That is, if we want to use this data, then as researchers we must go out and hunt it, if you like.</p>
</section>
<section id="randomization" class="level3" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="randomization"><span class="header-section-number">10.1.3</span> Randomization</h3>
<p>Correlation can be enough in some settings, but in order to be able to make forecasts when things change, and the circumstances are slightly different we need to understand causation. The key is the counterfactual: what would have happened in the absence of the treatment. Ideally, we could keep everything else constant, randomly divide the world into two groups, and treat one and not the other. Then we can be pretty confident that any difference between the two groups is due to that treatment. The reason for this is that if we have some population and we randomly select two groups from it, then our two groups (provided they are both big enough) should have the same characteristics as the population. Randomized controlled trials (RCTs) and A/B testing attempt to get us as close to this ‘gold standard’ as we can hope. When we, and others such as <span class="citation" data-cites="athey2017state">Athey and Imbens (<a href="references.html#ref-athey2017state" role="doc-biblioref">2017</a>)</span>, use language like gold standard to refer to these approaches, we do not mean to imply that they are perfect. Just that they can be better than most of the other options.</p>
<p>What we hope to be able to do is to find treatment and control groups that are the same, but for the treatment. This means that establishing the control group is critical because when we do that, we establish the counterfactual. We might be worried about, say, underlying trends, which is one issue with a before-and-after comparison, or selection bias, which could occur when we allow self-selection. Either of these issues could result in biased estimators. We use randomization to go some way to addressing these.</p>
<p>To get started, we simulate a population, and then randomly sample from it. We will set it up so that half the population likes blue, and the other half likes white. And further, if someone likes blue then they almost surely prefer dogs, but if they like white then they almost surely prefer cats. The approach of heavily using simulation is a critical part of the workflow advocated in this book. This is because we know roughly what the outcomes should be from the analysis of simulated data. Whereas if we go straight to analyzing the real data then we do not know if unexpected outcomes are due to our own analysis errors, or actual results. Another good reason it is useful to take this approach of simulation is that when you are working in teams the analysis can get started before the data collection and cleaning is completed. That simulation will also help the collection and cleaning team think about tests they should run on their data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>number_of_people <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>population <span class="ot">&lt;-</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">person =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span>number_of_people),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">favorite_color =</span> <span class="fu">sample</span>(</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="fu">c</span>(<span class="st">"Blue"</span>, <span class="st">"White"</span>),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">size  =</span> number_of_people,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">replace =</span> <span class="cn">TRUE</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">prefers_dogs_to_cats =</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">if_else</span>(favorite_color <span class="sc">==</span> <span class="st">"Blue"</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">noise =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">size =</span> <span class="dv">1</span>),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">prefers_dogs_to_cats =</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>      <span class="fu">if_else</span>(</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        noise <span class="sc">&lt;=</span> <span class="dv">8</span>,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>        prefers_dogs_to_cats,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>        <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>), </span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>noise)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>population</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,000 × 3
   person favorite_color prefers_dogs_to_cats
    &lt;int&gt; &lt;chr&gt;          &lt;chr&gt;               
 1      1 Blue           Yes                 
 2      2 White          No                  
 3      3 White          No                  
 4      4 Blue           Yes                 
 5      5 Blue           Yes                 
 6      6 Blue           Yes                 
 7      7 Blue           Yes                 
 8      8 Blue           Yes                 
 9      9 White          No                  
10     10 White          No                  
# … with 4,990 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>population <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(favorite_color) <span class="sc">|&gt;</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
# Groups:   favorite_color [2]
  favorite_color     n
  &lt;chr&gt;          &lt;int&gt;
1 Blue            2547
2 White           2453</code></pre>
</div>
</div>
<p>We will now construct a frame, assuming that we have a frame that contains 80 per cent of the population.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>frame <span class="ot">&lt;-</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  population <span class="sc">|&gt;</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">in_frame =</span> <span class="fu">sample</span>(</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">size  =</span> number_of_people,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.8</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">|&gt;</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(in_frame <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>frame <span class="sc">|&gt;</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(favorite_color) <span class="sc">|&gt;</span> </span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
# Groups:   favorite_color [2]
  favorite_color     n
  &lt;chr&gt;          &lt;int&gt;
1 Blue            2023
2 White           1980</code></pre>
</div>
</div>
<p>For now, we will set aside dog or cat preferences and focus on creating treatment and control groups on the basis of favorite color only.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  frame <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>prefers_dogs_to_cats) <span class="sc">|&gt;</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group =</span> <span class="fu">sample</span>(</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">c</span>(<span class="st">"Treatment"</span>, <span class="st">"Control"</span>),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">size  =</span> <span class="fu">nrow</span>(frame),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">replace =</span> <span class="cn">TRUE</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When we look at the mean for the two groups, we can see that the proportions that prefer blue or white are very similar to what we specified (<span class="quarto-unresolved-ref">?tbl-bluetowhite</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sample <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group, favorite_color) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>() <span class="sc">|&gt;</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">|&gt;</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"Preferred color"</span>, <span class="st">"Number"</span>, <span class="st">"Proportion"</span>),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">linesep =</span> <span class="st">""</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Proportion of the treatment and control group that prefer blue or white </caption>
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: left;">Preferred color</th>
<th style="text-align: right;">Number</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: left;">Blue</td>
<td style="text-align: right;">987</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">997</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Treatment</td>
<td style="text-align: left;">Blue</td>
<td style="text-align: right;">1036</td>
<td style="text-align: right;">0.51</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">983</td>
<td style="text-align: right;">0.49</td>
</tr>
</tbody>
</table>
</div>
</div>
<!-- We are probably convinced by looking at it, but to formally test if there is a difference in the two samples, we could use a t-test. -->
<!-- ```{r} -->
<!-- sample <-  -->
<!--   sample |> -->
<!--   mutate(color_as_integer =  -->
<!--            if_else(favorite_color == "White", 0, 1) -->
<!--   ) -->
<!-- treatment <-  -->
<!--   sample |>  -->
<!--   filter(group == "Treatment") |>  -->
<!--   select(color_as_integer) -->
<!-- control <-  -->
<!--   sample |>  -->
<!--   filter(group == "Control") |>  -->
<!--   select(color_as_integer) -->
<!-- t.test(treatment, control) -->
<!-- ``` -->
<p>We randomized based on favorite color. But we should also find that we took dog or cat preferences along at the same time and will have a ‘representative’ share of people who prefer dogs to cats. Why should that happen when we have not randomized on these variables? Let’s start by looking at our dataset (<a href="#tbl-dogstocats">Table&nbsp;<span>10.1</span></a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sample <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(frame <span class="sc">|&gt;</span> <span class="fu">select</span>(person, prefers_dogs_to_cats), </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="st">"person"</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group, prefers_dogs_to_cats) <span class="sc">|&gt;</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>() <span class="sc">|&gt;</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">|&gt;</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"Prefers dogs to cats"</span>, <span class="st">"Number"</span>, <span class="st">"Proportion"</span>),</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">linesep =</span> <span class="st">""</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-dogstocats" class="anchored">
<table class="table table-sm table-striped">
<caption>Table 10.1: Proportion of the treatment and control group that prefer dogs or cats</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: left;">Prefers dogs to cats</th>
<th style="text-align: right;">Number</th>
<th style="text-align: right;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">997</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">987</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Treatment</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">983</td>
<td style="text-align: right;">0.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">1036</td>
<td style="text-align: right;">0.51</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>It is exciting to have a representative share on ‘unobservables’. In this case, we do ‘observe’ them—to illustrate the point—but we did not select on them. We get this because the variables were correlated. But it will break down in several ways that we will discuss. It also assumes large enough groups. For instance, if we considered specific dog breeds, instead of dogs as an entity, we may not find ourselves in this situation. To check that the two groups are the same we look to see if we can identify a difference between the two groups based on observables. In this case we looked at the mean, but we could look at other aspects as well.</p>
<p>This all brings us to Analysis of Variation (ANOVA). ANOVA was introduced by Fisher while he was working on statistical problems in agriculture. This is less unexpected than it may seem as historically agricultural research has been closely tied to statistical innovation. We mention ANOVA here because of its importance historically, but it is a variant of linear regression which we cover in some detail in Chapter @ref(ijalm). Further, in general, we would usually not use ANOVA day-to-day. There is nothing wrong with it in the right circumstances. But it is more than a hundred years old and the number of modern use-case where it is the best option is small.</p>
<p>In any case, we approach ANOVA with the expectation that the groups are from the same distribution and could conduct it using <code>aov()</code>. In this case, we would fail to reject our default hypothesis that the samples are the same.</p>
</section>
<section id="treatment-and-control" class="level3" data-number="10.1.4">
<h3 data-number="10.1.4" class="anchored" data-anchor-id="treatment-and-control"><span class="header-section-number">10.1.4</span> Treatment and control</h3>
<p>If the treated and control groups are the same in all ways and remain that way, but for the treatment, then we have internal validity, which is to say that our control will work as a counterfactual and our results can speak to a difference between the groups in that study. Internal validity means that our estimates of the effect of the treatment are speaking to the treatment and not some other aspect. They mean that we can use our results to make claims about what happened in the experiment.</p>
<p>If the group to which we applied our randomization were representative of the broader population, and the experimental set-up were fairly similar to outside conditions, then we further could have external validity. That would mean that the difference we find does not just apply in our own experiment, but also in the broader population. External validity means that we can use our experiment to make claims about what would happen outside the experiment. It is randomization that has allowed that to happen.</p>
<p>But this means we need randomization twice. Firstly, into the group that was subject to the experiment, and then secondly, between treatment and control. How do we think about this randomization, and to what extent does it matter?</p>
<p>We are interested in the effect of being treated. It may be that we charge different prices, which would be a continuous treatment variable, or that we compare different colors on a website, which would be a discrete treatment variable. Either way, we need to make sure that all the groups are otherwise the same. How can we be convinced of this? One way is to ignore the treatment variable and to examine all other variables, looking for whether we can detect a difference between the groups based on any other variables. For instance, if we are conducting an experiment on a website, then are the groups roughly similar in terms of, say:</p>
<ul>
<li>Microsoft and Apple users?</li>
<li>Safari, Chrome, and Firefox users?</li>
<li>Mobile and desktop users?</li>
<li>Users from certain locations?</li>
</ul>
<p>Further, are the groups representative of the broader population? These are all threats to the validity of our claims.</p>
<p>But if done properly, that is if the treatment is truly independent, then we can estimate the average treatment effect (ATE). In a binary treatment variable setting this is:</p>
<p><span class="math display">\[\mbox{ATE} = \mathbb{E}[Y|t=1] - \mathbb{E}[Y|t=0].\]</span></p>
<p>That is, the difference between the treated group, <span class="math inline">\(t = 1\)</span>, and the control group, <span class="math inline">\(t = 0\)</span>, when measured by the expected value of the outcome, <span class="math inline">\(Y\)</span>. The ATE becomes the difference between the two expectations.</p>
<p>To illustrate this concept, we first simulate some data that shows a difference of one between the treatment and control groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>ate_example <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">person =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">was_treated =</span> <span class="fu">sample</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">x =</span> <span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">size  =</span> <span class="dv">1000</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">replace =</span> <span class="cn">TRUE</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                      ))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Make outcome a bit more likely if treated.</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>ate_example <span class="ot">&lt;-</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  ate_example <span class="sc">|&gt;</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">|&gt;</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome =</span> <span class="fu">if_else</span>(</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    was_treated <span class="sc">==</span> <span class="st">"No"</span>,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">mean =</span> <span class="dv">6</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see the difference, which we simulated to be one, between the two groups in Figure (<a href="#fig-exampleatefig">Figure&nbsp;<span>10.1</span></a>). And we can compute the average between the groups and then the difference to see also that we get back the result that we put in (<a href="#tbl-exampleatetable">Table&nbsp;<span>10.2</span></a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>ate_example <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> outcome,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill =</span> was_treated)) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Outcome"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of people"</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Person was treated"</span>) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-exampleatefig" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10-hunt_files/figure-html/fig-exampleatefig-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.1: Simulated data showing a difference between the treatment and control group</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>ate_example <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(was_treated) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(outcome)) <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> was_treated, <span class="at">values_from =</span> mean) <span class="sc">|&gt;</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">difference =</span> Yes <span class="sc">-</span> No) <span class="sc">|&gt;</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Average for treated"</span>, <span class="st">"Average for not treated"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">linesep =</span> <span class="st">""</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-exampleatetable" class="anchored">
<table class="table table-sm table-striped">
<caption>Table 10.2: Average difference between the treatment and control groups for data simulated to have an average difference of one</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Average for treated</th>
<th style="text-align: right;">Average for not treated</th>
<th style="text-align: right;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">6.06</td>
<td style="text-align: right;">1.06</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Unfortunately, there is often a difference between simulated data and reality. For instance, an experiment cannot run for too long otherwise people may be treated many times, or become inured to the treatment; but it cannot be too short otherwise we cannot measure longer term outcomes. We cannot have a ‘representative’ sample across every facet of a population, but if not, then the treatment and control will be different. Practical difficulties may make it difficult to follow up with certain groups and so we end up with a biased collection. Some questions to explore when working with real experimental data include:</p>
<ul>
<li>How are the participants being selected into the frame for consideration?</li>
<li>How are they being selected for treatment? We would hope this is being done randomly, but this term is applied to a variety of situations. Additionally, early ‘success’ can lead to pressure to treat everyone, especially in medical settings.</li>
<li>How is treatment being assessed?</li>
<li>To what extent is random allocation ethical and fair? Some argue that shortages mean it is reasonable to randomly allocate, but that may depend on how linear the benefits are. It may also be difficult to establish definitions, and the power imbalance between those making these decisions and those being treated should be considered.</li>
</ul>
<p>Bias and other issues are not the end of the world. But we need to think about them carefully. In a well-known example, Abraham Wald, the twentieth century Hungarian mathematician, was given data on the planes that came back to Britain after being shot at in WW2. The question was where to place the armor. One option was to place it over the bullet holes. Wald recognized that there is a selection effect here—these are the planes that made it back to be examined—so those holes did not necessarily need the armor. Arguably armor would be better placed where there were no bullet holes.</p>
<p>For instance, how would the results of a survey about the difficulty of a university course differ if only students who completed the course were surveyed, and not those who dropped out? While we should work to try to make our dataset as good as possible, it may be possible to use the model to control for some of the bias. For instance, if there was a variable that was correlated with say, attrition, then it could be added to the model either by-itself, or as an interaction. Similarly, if there was correlation between the individuals. For instance, if there was some ‘hidden variable’ that we did not know about that meant some individuals were correlated, then we could use ‘wider’ standard errors. This needs to be done carefully and we discuss this further in Chapter @ref(causality). That said, if such issues can be anticipated, then it can be better to change the experiment. For instance, perhaps it would be possibly to stratify by that hidden variable.</p>
<!-- **TBD: Add code** -->
</section>
<section id="fishers-tea-party" class="level3" data-number="10.1.5">
<h3 data-number="10.1.5" class="anchored" data-anchor-id="fishers-tea-party"><span class="header-section-number">10.1.5</span> Fisher’s tea party</h3>
<p>Fisher introduced an experiment designed to see if a person can distinguish between a cup of tea where the milk was added first, or last. We begin by preparing eight cups of tea: four with milk added first and the other four with milk added last. We then randomize the order of all eight cups. We tell the taster, whom we will call ‘Ian’, about the experimental set-up: there are eight cups of tea, four of each type, he will be given cups of tea in a random order, and the task is to group them into two groups.</p>
<p>One of the nice aspects of this experiment is that we can do it ourselves. There are a few things to be careful of in practice, including that: the quantities of milk and tea and consistent; the groups are marked in some way that the taster cannot see; and the order is randomized.</p>
<p>Another nice aspect of this experiment is that we can calculate the chance that Ian is able to randomly get the groupings correct. To decide if his groupings were likely to have occurred at random, we need to calculate the probability this could happen. First, we count the number of successes out of the four that were chosen. <span class="citation" data-cites="fisherdesignofexperiments">Fisher (<a href="references.html#ref-fisherdesignofexperiments" role="doc-biblioref">1935, 14</a>)</span> says there are: <span class="math inline">\({8 \choose 4} = \frac{8!}{4!(8-4)!}=70\)</span> possible outcomes.</p>
<p>We are asking Ian to group the cups, not to identify which is which, and so there are two ways for him to be perfectly correct. He could either correctly identify all the ones that were milk-first (one outcome out of 70) or correctly identify all the ones that were tea-first (one outcome out of 70). This means the probability of this event is: <span class="math inline">\(\frac{2}{70} \approx 0.028\)</span> or about 3 per cent.</p>
<p>As <span class="citation" data-cites="fisherdesignofexperiments">Fisher (<a href="references.html#ref-fisherdesignofexperiments" role="doc-biblioref">1935, 15</a>)</span> makes clear, this now becomes a judgement call. We need to consider the weight of evidence that we require before we accept the groupings did not occur by chance and that Ian was well-aware of what he was doing. We need to decide what evidence it takes for us to be convinced. If there is no possible evidence that would dissuade us from the view that we held coming into the experiment, say, that there is no difference between milk-first and tea-first, then what is the point of doing an experiment? We would expect that if Ian got it completely right, then most would accept that he was able to tell the difference.</p>
<p>What if he is almost perfect? By chance, there are 16 ways for a person to be ‘off-by-one’. Either Ian thinks there was one cup that was milk-first when it was tea-first—there are, <span class="math inline">\({4 \choose 1} = 4\)</span>, four ways this could happen—or he thinks there was one cup that was tea-first when it was milk-first—again, there are, <span class="math inline">\({4 \choose 1}\)</span> = 4, four ways this could happen. These outcomes are independent, so the probability is <span class="math inline">\(\frac{4\times 4}{70} \approx 0.228\)</span>. And so on. Given there is an almost 23 per cent chance of being off-by-one just be randomly grouping the teacups, this outcome probably would not convince us that Ian can tell the difference between tea-first and milk-first.</p>
<p>What we are looking for, in order to claim something is experimentally demonstrable is the results of not just it being shown once, but instead we know the features of an experiment where such a result is reliably found <span class="citation" data-cites="fisherdesignofexperiments">(<a href="references.html#ref-fisherdesignofexperiments" role="doc-biblioref">Fisher 1935, 16</a>)</span>. We are looking to thoroughly interrogate our data and our experiments, and to think precisely about the analysis methods we are using. Rather than searching for meaning in constellations of stars, we want to make it as easy as possible for others to reproduce our work. It is only in that way that our conclusions stand a chance of holding up in the long-term.</p>
</section>
<section id="informed-consent-and-the-need-for-an-experiment" class="level3" data-number="10.1.6">
<h3 data-number="10.1.6" class="anchored" data-anchor-id="informed-consent-and-the-need-for-an-experiment"><span class="header-section-number">10.1.6</span> Informed consent and the need for an experiment</h3>
<p>One of the foundations of ethical experimental practice is informed consent and ensuring that an experiment is actually needed. We will now detail two cases where human life was potentially lost due to these issues. One issue with experiments in medical settings is that the weight of evidence is measured in lost lives. Ethical practice in experiments develops because of the many people who may have unnecessarily lost their life due to experiments. Two cases that have dramatically informed practice are the Tuskegee Syphilis Study and ECMO.</p>
<p>The Tuskegee Syphilis Study is an infamous medical trial that began in 1932. As part of this experiment 400 Black Americans with syphilis, and a control group without, were not given appropriate treatment, nor even told they had syphilis (in the case of the treatment group), well after a standard treatment for syphilis was established and widely available sometime between the mid-1940s and early 1950s <span class="citation" data-cites="brandt1978racism tuskegeeandthehealthofblackmen">(<a href="references.html#ref-brandt1978racism" role="doc-biblioref">Brandt 1978</a>; <a href="references.html#ref-tuskegeeandthehealthofblackmen" role="doc-biblioref">Alsan and Wanamaker 2018</a>)</span>. Like the treatment group, the control group were also given non-effective drugs. These financially-poor Black Americans in the US South were identified and offered compensation including ‘hot meals, the guise of treatment, and burial payments’ <span class="citation" data-cites="tuskegeeandthehealthofblackmen">(<a href="references.html#ref-tuskegeeandthehealthofblackmen" role="doc-biblioref">Alsan and Wanamaker 2018</a>)</span>. The men were not actually treated for syphilis <span class="citation" data-cites="brandt1978racism tuskegeeandthehealthofblackmen">(<a href="references.html#ref-brandt1978racism" role="doc-biblioref">Brandt 1978</a>; <a href="references.html#ref-tuskegeeandthehealthofblackmen" role="doc-biblioref">Alsan and Wanamaker 2018</a>)</span>. The men were not told they were part of an experiment <span class="citation" data-cites="brandt1978racism tuskegeeandthehealthofblackmen">(<a href="references.html#ref-brandt1978racism" role="doc-biblioref">Brandt 1978</a>; <a href="references.html#ref-tuskegeeandthehealthofblackmen" role="doc-biblioref">Alsan and Wanamaker 2018</a>)</span>. Further, extensive work was undertaken to ensure the men would not receive treatment from anywhere including writing to local doctors, the local health department, and, incredibly, after some of the men were drafted and told to immediately get treatment, the draft board complied with a request to have the men excluded from treatment <span class="citation" data-cites="brandt1978racism">(<a href="references.html#ref-brandt1978racism" role="doc-biblioref">Brandt 1978, 25</a>)</span>. By the time the study was stopped in 1972, more than half of the men were deceased and many of deaths were from syphilis-related causes <span class="citation" data-cites="tuskegeeandthehealthofblackmen">(<a href="references.html#ref-tuskegeeandthehealthofblackmen" role="doc-biblioref">Alsan and Wanamaker 2018</a>)</span>.</p>
<p>The effect of the Tuskegee Syphilis Study was felt not just by the men in the study, but more broadly. <span class="citation" data-cites="tuskegeeandthehealthofblackmen">Alsan and Wanamaker (<a href="references.html#ref-tuskegeeandthehealthofblackmen" role="doc-biblioref">2018</a>)</span> found that it is associated with a decrease in life expectancy at age 45 of up to 1.5 years for Black men. In response the US established requirements for Institutional Review Boards and President Clinton made a formal apology in 1997. <span class="citation" data-cites="brandt1978racism">Brandt (<a href="references.html#ref-brandt1978racism" role="doc-biblioref">1978, 27</a>)</span> says:</p>
<blockquote class="blockquote">
<p>In retrospect the Tuskegee Study revealed more about the pathology of racism than the pathology of syphilis; more about the nature of scientific inquiry than the nature of the disease process… [T]he notion that science is a value-free discipline must be rejected. The need for greater vigilance in assessing the specific ways in which social values and attitudes affect professional behavior is clearly indicated.</p>
</blockquote>
<p>Turning to the evaluation of extracorporeal membrane oxygenation (ECMO), <span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989</a>)</span> describes how they viewed ECMO as a possible treatment for persistent pulmonary hypertension in newborns (PPHN). They enrolled 19 patients and used conventional medical therapy on ten of them, and ECMO on nine of them. It was found that six of the ten in the control group survived while all in the treatment group survived. <span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989</a>)</span> used randomized consent whereby only the parents of infants randomly selected to be treated with ECMO were asked to consent.</p>
<p><span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989</a>)</span> are concerned with ‘equipoise’, by which they refer to a situation in which there is genuine uncertainty about whether the treatment is more effective than existing procedures. They further note that in medical settings even if there is initial equipoise it could be undermined if the treatment is found to be effective early in the study. <span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989</a>)</span> describe how after the results of these first 19 patients, randomization stopped and only ECMO was used. The recruiters and those treating the patients were initially not told that randomization had stopped. It was decided that this complete allocation to ECMO would continue ‘until either the 28th survivor or the 4th death was observed’. After 19 of 20 additional patients survived ECMO the trial was terminated. So, the actual result of the experiment was divided into two phases: in the first there was randomized use of ECMO, and in the second only ECMO was used.</p>
<p>One approach in these settings is a ‘randomized play-the-winner’ rule following <span class="citation" data-cites="wei1978randomized">Wei and Durham (<a href="references.html#ref-wei1978randomized" role="doc-biblioref">1978</a>)</span>. Treatment is still randomized, but the weight of probability shifts with each successful treatment to make treatment more likely and there is some stopping rule. <span class="citation" data-cites="berry1989investigating">Berry (<a href="references.html#ref-berry1989investigating" role="doc-biblioref">1989</a>)</span> argues that the stopping rule in the case of <span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989</a>)</span> occurred before the study started and that there was no need for the study at all because equipoise never existed. <span class="citation" data-cites="berry1989investigating">Berry (<a href="references.html#ref-berry1989investigating" role="doc-biblioref">1989</a>)</span> re-visit the literature mentioned by <span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989</a>)</span> and find extensive evidence that ECMO was known to be effective. <span class="citation" data-cites="berry1989investigating">Berry (<a href="references.html#ref-berry1989investigating" role="doc-biblioref">1989</a>)</span> points out that there is almost never complete consensus and so one could almost always argue for the existence of equipoise even in the face of a substantial weight of evidence. <span class="citation" data-cites="berry1989investigating">Berry (<a href="references.html#ref-berry1989investigating" role="doc-biblioref">1989</a>)</span> further criticizes <span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989</a>)</span> for the use of randomized consent because of the potential that there may have been different outcomes for the infants subject to conventional therapy had their parents known there were other options. And instead, <span class="citation" data-cites="berry1989investigating">Berry (<a href="references.html#ref-berry1989investigating" role="doc-biblioref">1989</a>)</span> argues for the need for comprehensive patient registries, enabling the analysis of large datasets.</p>
<p>While the Tuskegee Syphilis Study and ECMO may seem quite far from our present circumstances, Dr Monica Alexander, Assistant Professor, University of Toronto explains that while it may be illegal to do this exact research these days, it does not mean that unethical research does not still happen. We see it all the time in machine learning applications in health and other areas. While we are not meant to explicitly discriminate and we are meant to get consent, it does not mean that we cannot implicitly discriminate without any type of buy-in at all. For instance, <span class="citation" data-cites="obermeyer2019dissecting">Obermeyer et al. (<a href="references.html#ref-obermeyer2019dissecting" role="doc-biblioref">2019</a>)</span> describes how US health care systems use algorithms to score the severity of how sick a patient is. They show that for the same score, ‘Black patients are considerably sicker than White patients, as evidenced by signs of uncontrolled illnesses’ and that if Black patients were scored in the same way as White patients, then they would receive considerably more help than they do now. They find that the discrimination occurs because the algorithm is based on health care costs, rather than sickness. But because access to healthcare is unequally distributed between Black and White patients, the algorithm, however inadvertently, perpetuates racial bias.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Shoulders of giants
</div>
</div>
<div class="callout-body-container callout-body">
<p>Marcella Alsan</p>
</div>
</div>
</section>
<section id="case-study-the-oregon-health-insurance-experiment" class="level3" data-number="10.1.7">
<h3 data-number="10.1.7" class="anchored" data-anchor-id="case-study-the-oregon-health-insurance-experiment"><span class="header-section-number">10.1.7</span> Case study: The Oregon Health Insurance Experiment</h3>
<p>In the US, unlike many developed countries, basic health insurance is not necessarily available to all residents even those on low incomes. The Oregon Health Insurance Experiment involved low-income adults in Oregon, a state in the north-west of the US, from 2008 to 2010 <span class="citation" data-cites="finkelstein2012oregon">(<a href="references.html#ref-finkelstein2012oregon" role="doc-biblioref">Finkelstein et al. 2012</a>)</span>.</p>
<p>Oregon funded 10,000 places in the state-run Medicaid program, which provides health insurance for people with low incomes. A lottery was used to allocate these places and was judged fair because it was expected, correctly as it turned out, that demand for places would exceed the supply. People had a month to sign up to enter the draw. Then a lottery was used to determine which of the 89,824 individuals who signed up would be allowed to apply for Medicaid.</p>
<p>The draws were conducted over a six-month period and those who were selected had the opportunity to sign up. 35,169 individuals were selected (the household of those who actually won the draw was given the opportunity) but only 30 per cent of them completed the paperwork and were eligible (typically they earned too much). The insurance lasted indefinitely. This random allocation of insurance allowed the researchers to understand the effect of health insurance.</p>
<p>The reason that this random allocation is important is that it is not usually possible to compare those with and without insurance because the type of people that sign up to get health insurance differ to those who do not. That decision is ‘confounded’ with other variables and results in a selection effect.</p>
<p>As the opportunity to apply for health insurance was randomly allocated, the researchers were able to evaluate the health and earnings of those who received health insurance and compare them to those who did not. To do this they used administrative data, such as hospital discharge data, credit reports that were matched to 68.5 per cent of lottery participants, and mortality records, which will be uncommon. Interestingly this collection of data is fairly restrained and so they included a survey conducted via mail.</p>
<p>The specifics of this are not important, and we will have more to say in Chapter @ref(ijalm), but they use a statistical model, <a href="#eq-oregon">Equation&nbsp;<span>10.1</span></a>, to analyze the results <span class="citation" data-cites="finkelstein2012oregon">(<a href="references.html#ref-finkelstein2012oregon" role="doc-biblioref">Finkelstein et al. 2012</a>)</span>:</p>
<p><span id="eq-oregon"><span class="math display">\[
y_{ihj} = \beta_0 + \beta_1\mbox{Lottery} + X_{ih}\beta+2 + V_{ih}\beta_3 + \epsilon_{ihj}
\tag{10.1}\]</span></span></p>
<p>Equation <a href="#eq-oregon">Equation&nbsp;<span>10.1</span></a> explains various <span class="math inline">\(j\)</span> outcomes (such as health) for an individual <span class="math inline">\(i\)</span> in household <span class="math inline">\(h\)</span> as a function of an indicator variable as to whether household <span class="math inline">\(h\)</span> was selected by the lottery. Hence, ‘(t)he coefficient on Lottery, <span class="math inline">\(\beta_1\)</span>, is the main coefficient of interest, and gives the average difference in (adjusted) means between the treatment group (the lottery winners) and the control group (those not selected by the lottery).’</p>
<p>To complete the specification of Equation <a href="#eq-oregon">Equation&nbsp;<span>10.1</span></a>, <span class="math inline">\(X_{ih}\)</span> is a set of variables that are correlated with the probability of being treated. These adjust for that impact to a certain extent. An example of that is the number of individuals in a household. And finally, <span class="math inline">\(V_{ih}\)</span> is a set of variables that are not correlated with the lottery. These variables include demographics, hospital discharge and lottery draw.</p>
<p>As has been found in earlier studies such as <span class="citation" data-cites="randhealth">Brook et al. (<a href="references.html#ref-randhealth" role="doc-biblioref">1984</a>)</span>, <span class="citation" data-cites="finkelstein2012oregon">Finkelstein et al. (<a href="references.html#ref-finkelstein2012oregon" role="doc-biblioref">2012</a>)</span> found that, the treatment group was 25 per cent more likely to have insurance than the control group. The treatment group used more health care including both primary and preventive care as well as hospitalizations but had lower out-of-pocket medical expenditures. More generally, the treatment group reported better physical and mental health.</p>
<!-- ### Case study: Student Coaching: How Far Can Technology Go? -->
<!-- There is a general concern about students dropping out of university before they finish their degree. If you work one-on-one with a student then this addresses the issue. But that doesn't scale. The point of this experiment was to see if technology-based options could be more efficient. The focus was the University of Toronto, and in particular first-year economics courses in Fall 2015. -->
<!-- The intervention was administered to students as part of an economics class. Students received 2 per cent of their grade for completing the exercise. The specific exercise depended on the group of the student. The intervention involved three treatments as well as a control group that was just given a Big Five personality traits test. Additional information that was obtained included 'the highest level of education obtained by students’ parents, the amount of education they expect to obtain, whether they are first-year or international students, and their work and study time plans for the upcoming year.' [@Oreopoulos2018, p. 6]. -->
<!-- The treatments were [@Oreopoulos2018, p. 4]: -->
<!-- 1. '[A] one-time, online exercise completed during the first two weeks of class in the fall'. This exercise was 'designed to get them thinking about the future they envision and the steps they could take in the upcoming year at U of T to help make that future a reality. They were told that the exercise was designed for their benefit and to take their time while completing it. The online module lasted approximately 60 to 90 minutes and led students through a series of writing exercises in which they wrote about their ideal futures, both at work and at home, what they would like to accomplish in the current year at U of T, how they intend on following certain study strategies to meet their goals, and whether they want to get involved with extracurricular activities at the university' [@Oreopoulos2018, p. 6]. -->
<!-- 2. '[T]he online intervention plus text and email messaging throughout the full academic year'. This involved the students being given 'the opportunity to provide their phone numbers and participate in a text and email messaging campaign lasting throughout both the fall semester in 2015 and the winter semester in 2016' [@Oreopoulos2018, p. 8]. All students in this group got the emails, but only those that provided phone numbers got the messages. They were able to opt out, but 'few chose to do so' [@Oreopoulos2018, p. 8]. This was a two-way interaction in which students could ask questions. Some asked for the 'locations of certain facilities on campus or how to stay on residence during the holiday break, while others said they need help with English skills or specific courses. Some students expressed relatively deep emotions, such as feeling anxious about family pressure to succeed in school or from doing poorly on an evaluation' [@Oreopoulos2018, p. 9]. A response was usually given within an hour. -->
<!-- 3. '[T]he online intervention plus one-on-one coaching in which students are assigned to upper-year undergraduate coaches'. 'Coaches were available to meet with students to answer any questions via Skype, phone, or in person, and would send their students regular text and email messages of advice, encouragement, and motivation, much like the You@UofT program described above. In contrast to the messaging program, however, coaches were instructed to be proactive and regularly monitor their students’ progress. Whereas the You@UofT program attempts to “nudge” students in the right direction with academic advice, coaches play a greater “support” role, sensitively guiding students through problems.' [@Oreopoulos2018, p. 11]. This coaching program was only available at UTM. 'Our coaching treatment group was established by randomly drawing twenty-four students from the group of students that were randomly assigned into the text message campaign treatment. At the conclusion of the online exercise, instead of being invited to provide a phone number for the purpose of receiving text messages, these twenty-four students were given the opportunity to participate in a pilot coaching program. A total of seventeen students agreed to participate in the coaching program, while seven students declined.' -->
<!-- > Our coaching treatment group was established by randomly drawing twenty-four students from the group of students that were randomly assigned into the text message campaign treatment. At the conclusion of the online exercise, instead of being invited to provide a phone number for the purpose of receiving text messages, these twenty-four students were given the opportunity to participate in a pilot coaching program. A total of seventeen students agreed to participate in the coaching program, while seven students declined.  -->
<!-- > -->
<!-- > [@Oreopoulos2018, p. 14] -->
<!-- The model they consider is [@Oreopoulos2018, p. 15]: -->
<!-- \begin{equation} -->
<!-- y_{ij} = \alpha + \beta_1\mbox{Online}_i + \beta_2\mbox{Text}_i + + \beta_3\mbox{Coach}_i + \delta_j + \mu \mbox{First year}_i + \epsilon_{ij} (\#eq:toronto) -->
<!-- \end{equation} -->
<!-- Equation \@ref(eq:toronto) explains the outcome of student $i$ at campus $j$ based on 'indicators for each of the three treatment exercises students were given, campus fixed effects, and a first-year student indicator.' The main parameters of interest are $\beta_1$, $\beta_2$ and $\beta_3$. The main outcomes were course grades, GPA, credits earned and failed. -->

<!-- It was found, that the one-on-one coaching 'increased grades by approximately 5 percentage points', while the other treatments had 'had no detectable impact'. One set of results are summarised in @fig-torontointervention). -->
<!-- 
#| fig-cap: "Example of the results of the intervention."} --
#| echo: false
#| label: torontointervention
<!-- ![](figures/toronto_intervention.png")) -{#fig- width=95% fig-align="center"}
# out-width: "90"
>
<!-- ``` -->
<!-- The results are important not only in a teaching context, but also for businesses hoping to retain customers. More papers are available [here](https://www.povertyactionlab.org/evaluation/student-coaching-how-far-can-technology-go). -->
<!-- ### Case study: Civic Honesty Around The Globe -->
<!-- Trust isn't something that we think regularly about, but it is actually fairly fundamental to most interactions, both economic and personal. For instance, many of us get paid after we do some work - we are trusting our employer will make good; and vice versa - if you get paid in advance then they are trusting you. In a strictly naive, one-shot, transaction-cost-less world, this doesn't make sense. If you get paid in advance, the incentive is for you to take the money and run in the last pay period before you quit, and through backward induction everything falls apart. Of course, we do not live in such a world. For one thing there are transaction costs, for another generally we have repeated interactions, and finally, in my experience, the world usually ends up being fairly small.  -->
<!-- Understanding the extent of honestly in different countries may help us to explain economic development and other aspects of interest such as tax compliance, but it is fairly hard to measure. We can't really ask people how honest they are - wouldn't the liars lie, resulting in a lemons problem [@akerlof1978market]? To get around, this @cohn2019civic conduct an experiment in 355 cities across 40 countries where they 'turn in' either: a wallet with the local equivalent of US$13.45 in it, or no money. They are interested in whether the 'recipient' attempts to return the wallet. They find that '[in virtually all countries, citizens were more likely to return wallets that contained more money' [@cohn2019civic, p. 1].  -->
<!-- The set-up of the experiment is fascinating. They 'turn in' 17,303 wallets to various institutions including: '(i) banks; (ii) theaters, museums, or other cultural establishments; (iii) post offices; (iv) hotels; and (v) police stations, courts of law, or other public offices' [@cohn2019civic, p. 1]. These institutions were roughly equally sampled, although banks were slightly over sampled and post offices were slightly under-sampled. The importance of such institutions in the economy is generally well-accepted [@acemoglu2001colonial] and they are common across most countries. Importantly for the experiment, they 'typically have a public reception area where we could perform the drop-offs' [@cohn2019civic, p. 1]. -->
<!-- The way the experiment worked is that a research assistant turned the wallet in to an employee at a counter in the public reception area, saying 'Hi, I found this [showing the wallet] on the street just around the corner. [Place wallet on counter.] Somebody must have lost it. I'm in a hurry and have to go. Can you please take care of it?' [@cohn2019civic, p. 2]. The outcome of interest is whether an email is sent to the unique address on a business card in the wallet within 100 days. The research assistant had to note various features of the setting, including features such as the gender, age-group, and busyness of the 'recipient'. -->
<!-- The wallets were transparent, and the business card had a name and email contact details. It also had a key and a grocery list (@fig-walletsexample)). -->
<!-- 
#| fig-cap: "Example of the wallet."} --
#| echo: false
#| label: walletsexample
<!-- ![](figures/wallet_e{#fig- width=95% fig-align="center"}
# out-width: "90"
ample.png")) -->
<!-- ```  -->
<!-- The grocery list was an attempt to convince the 'recipient' that the 'owner' was a local. Language and currency were adapted to local conditions. The key is only useful to the 'owner', not to the 'recipient' of the wallet and was included to test for altruistic concerns. -->
<!-- The primary treatment in the experiment is whether the wallet contained money or not. The key outcome was whether the wallet was attempted to be returned or not. It was found that '[t]he median response time was roughly 26 minutes across all countries, and about 88% of emails arrived within 24 hours' [@cohn2019civicaddendum, p. 10]. If an email was received, then 3 hours later a response was sent, saying that the owner had left town, the contents were unimportant to them and that they could keep it or donate it to charity [@cohn2019civicaddendum, p. 9].  -->
<!-- Considerable differences were found between countries (@fig-wallets)). -->
<!-- 
#| fig-cap: "Key finding as to wallet return rates."} --
#| echo: false
#| label: wallets
<!-- ![](figures/wallet_results.png")) --{#fig- width=95% fig-align="center"}
# out-width: "90"

<!-- ```  -->
<!-- @fig-wallets) shows that in almost all countries wallets with money were more likely to be returned than wallets without. The authors further conducted the experiment with the equivalent of US$94.15 in three countries - Poland, the UK, and the US - and found that reporting rates further increased. In those same three countries further tests were done comparing the situation when the wallet always contained money, but the presence of the key was varied. The wallet was slightly more likely to be reported when there was a key. -->
<!-- The full set of 40 countries were chosen based on having enough cities with populations of at least 100,000, as well as the ability for the research assistants to safely visit and withdraw cash. The cities were chosen starting with the largest ones and there were usually 400 observations in each country [@cohn2019civicaddendum, p. 5]. Real-world concerns affected the specifics of the experiment. For instance, in '...India, we made a last minute change by replacing Chennai with Coimbatore due to severe flooding that took place in February 2015. In Kenya we did not carry out data collection in the last city visited (Malindi) because the research assistant was arrested and interrogated by the military police for suspicious activity' [@cohn2019civicaddendum, p. 5]. -->
<!-- In addition to the experiments, @cohn2019civic conducted surveys that allowed them to understand some reasons for their findings. It also allowed them to be specific about the respondents. The survey involved 2,525 respondents (829 in the UK, 809 in Poland, and 887 in the US) [@cohn2019civicaddendum, p. 36]. 'To qualify for participation, individuals had to pass a simple attention check and meet the demographic quotas (based on age, gender, and residence) set by Qualtrics to construct the representative samples. Participants received a flat payment of US $4.00 for their participation' [@cohn2019civicaddendum, p. 36]. The participants were given one of the scenarios and then asked to answer questions.  -->
<!-- Annoyingly the authors do not explicitly specify the estimating equation. However they do say that important covariates about the 'recipient' include: gender, age-group, busyness, whether they were local, spoke English, understood the situation, friendliness, presence of: a computer, co-workers, bystanders, security cameras, security guards. Important covariates at a country-level include: country GDP, soil fertility, latitude, distance to water, temperature and its volatility, precipitation and its volatility, elevation, terrain roughness, pathogens, language features such as: pronouns, politeness, future time; share of protestants; family ties; state history; years of democracy; executive constraints; judicial independence; constitutional review; electoral rule; and primary school enrollment in 1920.  -->
<!-- The code or data for the paper are available: @walletsdata. -->
</section>
</section>
<section id="ab-testing" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="ab-testing"><span class="header-section-number">10.2</span> A/B testing</h2>
<p>The past decade has probably seen the most experiments ever run by several orders of magnitude with the extensive use of A/B testing on websites. Large tech companies typically have extensive infrastructure for these experiments, and they term them A/B tests because of the comparison of two groups: one that gets treatment A and the other that either gets treatment B or does not see any change <span class="citation" data-cites="Salganik2018">(<a href="references.html#ref-Salganik2018" role="doc-biblioref">Salganik 2018, 185</a>)</span>. Every time you are online you are probably subject to tens, hundreds, or potentially thousands, of different A/B tests. If you use apps like TikTok then this could run to the tens of thousands. While, at their heart, they are still just surveys that result in data that need to be analysed, they have several interesting features that we will discuss.</p>
<p>For instance, <span class="citation" data-cites="kohavi">Kohavi, Tang, and Xu (<a href="references.html#ref-kohavi" role="doc-biblioref">2020, 3</a>)</span> discusses the example of Microsoft’s search engine Bing where they increased the amount of content displayed by their ads. The change triggered an alert that usually signaled a bug in the billing. But there was no bug, it was instead the case that revenue would increase by 12 per cent, or around $100 million annually in the US, without any significant trade-off being measured.</p>
<p>We use the term A/B test to strictly refer to the situation in which we are primarily implementing an experiment through a technology stack about something that is primarily of the internet, for instance a change to a website or similar. While at their heart they are just experiments, A/B testing has a range of specific concerns. There is something different about doing tens of thousands of small experiments all the time, compared with our normal experimental set-up of conducting one experiment over the course of months. Additionally, tech firms have such distinct cultures that it can be difficult to shift toward an experimental set-up. Sometimes it can be easier to experiment by not delivering, or delaying, a change that has been decided to create a control group rather than a treatment group <span class="citation" data-cites="Salganik2018">(<a href="references.html#ref-Salganik2018" role="doc-biblioref">Salganik 2018, 188</a>)</span>. Often the most difficult aspect of A/B testing and conducting experiments more generally, is not the statistics, it’s the politics.</p>
<p>The first aspect of concern is the delivery of the A/B test <span class="citation" data-cites="kohavi">(<a href="references.html#ref-kohavi" role="doc-biblioref">Kohavi, Tang, and Xu 2020, 153–61</a>)</span>. In the case of an experiment, it is usually clear how it is being delivered. For instance, we may have the person come to a doctor’s clinic and then inject them with either a drug or a placebo. But in the case of A/B testing, it is less obvious. For instance, should it be run ‘server-side’, meaning to make a change to a website, or ‘client-side’, meaning to change an app. This decision affects our ability to both conduct the experiment and to gather data from it.</p>
<p>In the case of the effect of conducting the experiment, it is relatively easy and normal to update a website all the time. This means that small changes can be easily implemented if the experiment is conducted server-side. But in the case of a client-side implementation of an app, then conducting an experiment becomes a bigger deal. For instance, the release may need to go through an app store, and this usually does not happen all the time. Instead, it would need to be part of a regular release cycle. There is also a selection concern because some users will not update their app and there is the possibility that they are different to those that do regularly update the app.</p>
<p>Turning to the effect of the delivery decision on our ability to gather data from the experiment. Again, server-side is less of a big deal because we get the data anyway as part of the user interacting with the website. But in the case of an app, the user may use the app offline or with limited data upload, which then requires a data transmission protocol or caching, but this then could affect user experience, especially as some phones place limits are various aspects.</p>
<p>The effect of all this is that we need to plan. For instance, results are unlikely to be available the day after a change to an app, whereas they are likely available the day after a change to a website. Further, we may need to consider our results in the context of different devices and platforms, potentially using, say, multilevel regression which will be covered in Chapter @ref(ijalm).</p>
<p>The second aspect of concern is ‘instrumentation’ or the method of measurement <span class="citation" data-cites="kohavi">(<a href="references.html#ref-kohavi" role="doc-biblioref">Kohavi, Tang, and Xu 2020, 162</a> - 165)</span>. When we conduct a traditional experiment then we might, for instance, ask respondents to fill out a survey. But this is usually not done with A/B testing. One approach is to put a cookie on the user’s device, but different users will clear these at different rates. Another approach is to use a beacon, such as forcing the user to download a tiny image from our server, so that we know when they have completed some action. For instance, this is a commonly used approach to know when a user has opened an email. There are practical concerns around when the beacon loads, for instance, if it is before the main content loads then the user experience may be worse, but if it is after then our sample may be biased.</p>
<p>The third aspect of concern is what are we randomizing over <span class="citation" data-cites="kohavi">(<a href="references.html#ref-kohavi" role="doc-biblioref">Kohavi, Tang, and Xu 2020, 162</a> - 165)</span>. In the case of traditional experiments, this is usually clear and it is often a person, but sometimes various groups of people. But in the case of A/B testing it can be less clear. For instance, are we randomizing over the page, the session, or the user?</p>
<p>To think about this, let us consider color. For instance, say we are interested in whether we should change our logo from red to blue on the homepage. If we are randomizing at the page level, then if the user goes to some other page of our website, and then back to the homepage the logo could be back to red. If we are randomizing at the session level, then while it could be blue while they use the website this time, if they close it and come back then it could be red. Finally, if we are randomizing at a user level then possibly it would always be red for one used, but always blue for another.</p>
<p>The extent to which this matters depends on a trade-off between consistency and importance. For instance, if we are A/B testing product prices then consistency is likely a feature. But if we are A/B testing background colors then consistency might not be as important. On the other hand, if we are A/B testing the position of a log-in button then it might be important that we not move that around too much for the one user, but between users it might matter less.</p>
<p>Interestingly, in A/B testing, as in traditional experiments, we are concerned that our treatment and control groups are the same, but for the treatment. In the case of traditional experiments, we satisfy ourselves of this by making conducting analysis on the basis of the data that we have after the experiment is conducted. That is usually all we can do because it would be weird to treat or control both groups. But in the case of A/B testing, the pace of experimentation allows us to randomly create the treatment and control groups, and then check, before we subject the treatment group to the treatment, that the groups are the same. For instance, if we were to show each group the same website, then we would expect the same outcomes across the two groups. If we found different outcomes then we would know that we may have a randomization issue <span class="citation" data-cites="taddy2019">(<a href="references.html#ref-taddy2019" role="doc-biblioref">Taddy 2019, 129</a>)</span>.</p>
<p>One of the interesting aspects of A/B testing is that we are usually running them not because we desperately care about the specific outcome, but because that feeds into some other measure that we care about. For instance, do we care whether the website is quite-dark-blue or slightly-dark-blue? Probably not, but we probably care a lot about the company share price. But then what if picking the best blue comes at a cost to the share price? That example is a bit contrived, so let us pretend that we work at a food delivery app and we are concerned with driver retention. Say we do some A/B tests and find that drivers are always more likely to be retained when they can deliver food to the customer faster. Our finding is that faster is better, for driver retention, always. But one way to achieve faster deliveries, is for them to not put the food into a hot box that would maintain the food’s temperature. Something like that might save 30 seconds, which is significant on a 10-15 minute delivery. Unfortunately, although we would decide to encourage that that on the basis of A/B tests designed to optimize driver-retention, such a decision would likely make the customer experience worse. If customers receive cold food, when it is meant to be hot, then they may stop using the app, which would ultimately be very bad for the business.</p>
<p>This trade-off may be obvious when we run the driver experiment if we were to look at customer complaints. It is possible that on a small team we would be exposed to those tickets, but on a larger team we may not be. Ensuring that A/B tests are not resulting in false optimization is especially important. And not something that we typically have to worry about in normal experiments.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Shoulders of giants
</div>
</div>
<div class="callout-body-container callout-body">
<p>Susan Athey</p>
</div>
</div>
<section id="case-study-upworthy" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="case-study-upworthy"><span class="header-section-number">10.2.1</span> Case study: Upworthy</h3>
<p>The trouble with much of A/B testing is that it is done by firms and so we typically do not have datasets that we can use. But <span class="citation" data-cites="upworthy">Matias et al. (<a href="references.html#ref-upworthy" role="doc-biblioref">2019</a>)</span> provide access to a dataset of A/B tests from Upworthy, a clickbait media website that used A/B testing to optimize their content. <span class="citation" data-cites="aboutupworthy">Fitts (<a href="references.html#ref-aboutupworthy" role="doc-biblioref">2014</a>)</span> provides more background information about Upworthy. And the datasets of A/B tests are available: https://osf.io/jd64p/.</p>
<p>We can look at what the dataset looks like, and get a sense for it by looking at the names and an extract.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>upworthy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://osf.io/vy8mj/download"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>upworthy <span class="sc">|&gt;</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "...1"                 "created_at"           "updated_at"          
 [4] "clickability_test_id" "excerpt"              "headline"            
 [7] "lede"                 "slug"                 "eyecatcher_id"       
[10] "impressions"          "clicks"               "significance"        
[13] "first_place"          "winner"               "share_text"          
[16] "square"               "test_week"           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>upworthy <span class="sc">|&gt;</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 17
   ...1 created_at          updated_at          clickability_test_id     excerpt
  &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;              &lt;chr&gt;                    &lt;chr&gt;  
1     0 2014-11-20 06:43:16 2016-04-02 16:33:38 546d88fb84ad38b2ce000024 Things…
2     1 2014-11-20 06:43:44 2016-04-02 16:25:54 546d88fb84ad38b2ce000024 Things…
3     2 2014-11-20 06:44:59 2016-04-02 16:25:54 546d88fb84ad38b2ce000024 Things…
4     3 2014-11-20 06:54:36 2016-04-02 16:25:54 546d902c26714c6c44000039 Things…
5     4 2014-11-20 06:54:57 2016-04-02 16:31:45 546d902c26714c6c44000039 Things…
6     5 2014-11-20 06:55:07 2016-04-02 16:25:54 546d902c26714c6c44000039 Things…
# … with 12 more variables: headline &lt;chr&gt;, lede &lt;chr&gt;, slug &lt;chr&gt;,
#   eyecatcher_id &lt;chr&gt;, impressions &lt;dbl&gt;, clicks &lt;dbl&gt;, significance &lt;dbl&gt;,
#   first_place &lt;lgl&gt;, winner &lt;lgl&gt;, share_text &lt;chr&gt;, square &lt;chr&gt;,
#   test_week &lt;dbl&gt;</code></pre>
</div>
</div>
<p>It is also useful to look at the documentation for the dataset. This describes the structure of the dataset, which is that there are packages within tests. A package is a collection of headlines and images that were shown randomly to different visitors to the website, as part of a test. A test can include many packages. Each row in the dataset is a package and the test that it is part of is specified by the ‘clickability_test_id’ column.</p>
<p>There are a variety of variables. We will focus on:</p>
<ul>
<li>‘created_at’,</li>
<li>‘clickability_test_id’ so that we can create comparison groups,</li>
<li>‘headline’,</li>
<li>‘impressions’ which is the number of people that saw the package, and</li>
<li>‘clicks’ which is the number that clicked on that package.</li>
</ul>
<p>Within each batch of tests, we are interested in the effect of the varied headlines on impressions and clicks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>upworthy_restricted <span class="ot">&lt;-</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  upworthy <span class="sc">|&gt;</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(created_at, clickability_test_id, headline, impressions, clicks)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(upworthy_restricted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  created_at          clickability_test_id     headline       impressions clicks
  &lt;dttm&gt;              &lt;chr&gt;                    &lt;chr&gt;                &lt;dbl&gt;  &lt;dbl&gt;
1 2014-11-20 06:43:16 546d88fb84ad38b2ce000024 They're Being…        3052    150
2 2014-11-20 06:43:44 546d88fb84ad38b2ce000024 They're Being…        3033    122
3 2014-11-20 06:44:59 546d88fb84ad38b2ce000024 They're Being…        3092    110
4 2014-11-20 06:54:36 546d902c26714c6c44000039 This Is What …        3526     90
5 2014-11-20 06:54:57 546d902c26714c6c44000039 This Is What …        3506    120
6 2014-11-20 06:55:07 546d902c26714c6c44000039 This Is What …        3380     98</code></pre>
</div>
</div>
<p>We will focus on the text contained in headlines, and look at whether headlines that asked a question got more clicks than those that did not. We want to remove the effect of different images and so will focus on those tests that have the same image. To identify whether a headline asks a question, we search for a question mark. Although there are more complicated constructions that we could use, this is enough to get started.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>upworthy_restricted <span class="ot">&lt;-</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  upworthy_restricted <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">asks_question =</span> <span class="fu">str_detect</span>(<span class="at">string =</span> headline, <span class="at">pattern =</span> <span class="st">"</span><span class="sc">\\</span><span class="st">?"</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>upworthy_restricted <span class="sc">|&gt;</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(asks_question)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  asks_question     n
  &lt;lgl&gt;         &lt;int&gt;
1 FALSE         19130
2 TRUE           3536</code></pre>
</div>
</div>
<p>For every test, and for every picture, we want to know whether asking a question affected the number of clicks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>to_question_or_not_to_question <span class="ot">&lt;-</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  upworthy_restricted <span class="sc">|&gt;</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clickability_test_id, asks_question) <span class="sc">|&gt;</span> </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">ave_clicks =</span> <span class="fu">mean</span>(clicks)) <span class="sc">|&gt;</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'clickability_test_id'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>look_at_differences <span class="ot">&lt;-</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  to_question_or_not_to_question <span class="sc">|&gt;</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> clickability_test_id,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">names_from =</span> asks_question,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> ave_clicks) <span class="sc">|&gt;</span> </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">ave_clicks_not_question =</span> <span class="st">`</span><span class="at">FALSE</span><span class="st">`</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ave_clicks_is_question =</span> <span class="st">`</span><span class="at">TRUE</span><span class="st">`</span>) <span class="sc">|&gt;</span> </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ave_clicks_not_question)) <span class="sc">|&gt;</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ave_clicks_is_question)) <span class="sc">|&gt;</span> </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">difference_in_clicks =</span> ave_clicks_is_question <span class="sc">-</span> ave_clicks_not_question)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>look_at_differences<span class="sc">$</span>difference_in_clicks <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -4.890435</code></pre>
</div>
</div>
<p>We find that in general, having a question in the headline may slightly decrease the number of clicks on a headline, although if there is an effect it does not appear to be very large (<a href="#fig-upworthy">Figure&nbsp;<span>10.2</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-upworthy" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="10-hunt_files/figure-html/fig-upworthy-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.2: Comparison of the average number of clicks when a headline contains a question mark or not</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="implementing-surveys" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="implementing-surveys"><span class="header-section-number">10.3</span> Implementing surveys</h2>
<p>There are many ways to implement surveys. For instance, there are dedicated survey platforms such as Survey Monkey and Qualtrics. In general, the focus of those platforms is on putting together the survey form and they expect that we already have contact details for the sample of interest. Some other platforms, such as Mechanical Turk and Prolific, focus on providing that audience, and we can then ask that audience to do more than just take a survey. While that is useful, it usually comes with higher costs. Finally, platforms such as Facebook also provide the ability to run a survey. One especially common approach, because it is free, is to use Google Forms.</p>
<p>To create a survey with Google Forms, sign into your Google Account, go to Google Drive, and then click ‘New’ then ‘Google Form’. By default, the form is largely empty (<a href="#fig-googleformfirst">Figure&nbsp;<span>10.3</span></a>), and we should add a title and description.</p>
<div id="fig-googleformfirst" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/googleformfirst.png" class="img-fluid figure-img" style="width:85.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.3: The default view when a new Google Form is created contains many empty fields</figcaption><p></p>
</figure>
</div>
<p>By default, an multiple-choice question is included, and we can update the content of this by clicking in the question field. Helpfully, there are often suggestions that can help provide the options. We can make the question required by toggling (<a href="#fig-googleformsecond">Figure&nbsp;<span>10.4</span></a>).</p>
<div id="fig-googleformsecond" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/googleformsecond.png" class="img-fluid figure-img" style="width:85.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.4: Updating the multiple-choice question that is included by default</figcaption><p></p>
</figure>
</div>
<p>We can add another question, by clicking on the plus with a circle around it, and select different types of question, for instance, ‘Short answer’, ‘Checkboxes’, or ‘Linear scale’ (<a href="#fig-googleformthird">Figure&nbsp;<span>10.5</span></a>). It can be especially useful to use ‘Short answer’ for aspect such as name and email address, checkboxes and linear scale to understand preferences.</p>
<div id="fig-googleformthird" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/googleformthird.png" class="img-fluid figure-img" style="width:85.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.5: Different options for questions include short answer, checkboxes, and linear scale</figcaption><p></p>
</figure>
</div>
<p>When we are happy with our survey, we make like to preview it ourselves, by clicking on the icon that looks like an eye. After checking it that way, we can click on ‘Send’. Usually it is especially useful to use the second option, which is to send via a link, and it can be handy to shorten the URL (<a href="#fig-googleformfourth">Figure&nbsp;<span>10.6</span></a>)).</p>
<div id="fig-googleformfourth" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/googleformfourth.png" class="img-fluid figure-img" style="width:85.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.6: There are a variety of ways to share the survey, and one helpful one is to get a link with a short URL</figcaption><p></p>
</figure>
</div>
<p>After you share your survey, results will accrue in the ‘Responses’ tab and it can be especially useful to create a spreadsheet to view these responses, by clicking on the ‘Sheets’ icon. After you have collected enough responses then you can turn off ‘Accepting responds’ (<a href="#fig-googleformfifth">Figure&nbsp;<span>10.7</span></a>).</p>
<div id="fig-googleformfifth" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/googleformfifth.png" class="img-fluid figure-img" style="width:85.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.7: Responses show up alongside the survey and it can be helpful to add those to a separate spreadsheet</figcaption><p></p>
</figure>
</div>
<!-- ## Sensor data -->
<!-- ## FOI -->
<!-- - Walby, Kevin and Alex Luscombe, eds. Freedom of Information and Social Science Research Design. New York: Routledge. -->
<!-- ## Next steps -->
<!-- Large scale experiments are happening all around us. These days I feel we all know a lot more about healthcare experiments than perhaps we'd like to know and the AstraZeneca/Oxford situation is especially interesting, for instance, @OxfordAstraZeneca, but see @Bastian2020 for how this is actually possibly more complicated. -->
<!-- There are also well-known experiments that tried to see if big government programs are effective, such as: -->
<!-- - The RAND Health Insurance Experiment randomly gave health insurance to people in the US between 1974 and 1982 [@randhealth]. -->
</section>
<section id="exercises-and-tutorial" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="exercises-and-tutorial"><span class="header-section-number">10.4</span> Exercises and tutorial</h2>
<section id="exercises" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="exercises"><span class="header-section-number">10.4.1</span> Exercises</h3>
<ol type="1">
<li><em>(Plan)</em> Consider the following scenario: <strong>TBD</strong>. Please sketch out what that dataset could look like and then sketch a graph that you could build to show all observations.</li>
<li><em>(Simulate)</em> Please further consider the scenario described and simulate the situation with every variable independent of each other.</li>
<li><em>(Acquire)</em> Please describe three possible sources of such a dataset.</li>
<li><em>(Explore)</em> Please use <code>ggplot2</code> to build the graph that you sketched.</li>
<li><em>(Communicate)</em> Please write two paragraphs about what you did.</li>
<li>In your own words, what is the role of randomization in constructing a counterfactual (write two or three paragraphs)?</li>
<li>What is external validity (pick one)?
<ol type="a">
<li>Findings from an experiment hold in that setting.</li>
<li>Findings from an experiment hold outside that setting.</li>
<li>Findings from an experiment that has been repeated many times.</li>
<li>Findings from an experiment for which code and data are available.</li>
</ol></li>
<li>What is internal validity (pick one)?
<ol type="a">
<li>Findings from an experiment hold in that setting.</li>
<li>Findings from an experiment hold outside that setting.</li>
<li>Findings from an experiment that has been repeated many times.</li>
<li>Findings from an experiment for which code and data are available.</li>
</ol></li>
<li>If we have a dataset named ‘netflix_data’, with the columns ‘person’ and ‘tv_show’ and ‘hours’, (person is a character class uniqueID for every person, tv_show is a character class name of a tv show, and hours is double expressing the number of hours that person watched that tv show). Could you please write some code that would randomly assign people into one of two groups? The data looks like this:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>netflix_data <span class="ot">&lt;-</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">person =</span> <span class="fu">c</span>(<span class="st">"Rohan"</span>, <span class="st">"Rohan"</span>, <span class="st">"Monica"</span>, <span class="st">"Monica"</span>, <span class="st">"Monica"</span>, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Patricia"</span>, <span class="st">"Patricia"</span>, <span class="st">"Helen"</span>),</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">tv_show =</span> <span class="fu">c</span>(<span class="st">"Broadchurch"</span>, <span class="st">"Duty-Shame"</span>, <span class="st">"Broadchurch"</span>, <span class="st">"Duty-Shame"</span>, </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Shetland"</span>, <span class="st">"Broadchurch"</span>, <span class="st">"Shetland"</span>, <span class="st">"Duty-Shame"</span>),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">hours =</span> <span class="fu">c</span>(<span class="fl">6.8</span>, <span class="fl">8.0</span>, <span class="fl">0.8</span>, <span class="fl">9.2</span>, <span class="fl">3.2</span>, <span class="fl">4.0</span>, <span class="fl">0.2</span>, <span class="fl">10.2</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="5" type="1">
<li>In the context of randomization, what does stratification mean to you (write a paragraph or two)?</li>
<li>How could you check that your randomization had been done appropriately (write two or three paragraphs)?</li>
<li>Identify three companies that conduct A/B testing commercially and write one paragraph for each of them about how they work and the trade-offs involved.</li>
<li>Pretend that you work as a junior analyst for a large consulting firm. Further, pretend that your consulting firm has taken a contract to put together a facial recognition model for the Canada Border Services Agency’s Inland Enforcement branch. Taking a page or two, please discuss your thoughts on this matter. What would you do and why?</li>
<li>What is an estimate (pick one)?
<ol type="a">
<li>A rule for calculating an estimate of a given quantity based on observed data.</li>
<li>The quantity of interest.</li>
<li>The result.</li>
<li>Unknown numbers that determine a statistical model.</li>
</ol></li>
<li>What is an estimator (pick one)?
<ol type="a">
<li>A rule for calculating an estimate of a given quantity based on observed data.</li>
<li>The quantity of interest.</li>
<li>The result.</li>
<li>Unknown numbers that determine a statistical model.</li>
</ol></li>
<li>What is an estimand (pick one)?
<ol type="a">
<li>A rule for calculating an estimate of a given quantity based on observed data.</li>
<li>The quantity of interest.</li>
<li>The result.</li>
<li>Unknown numbers that determine a statistical model.</li>
</ol></li>
<li>What is a parameter (pick one)?
<ol type="a">
<li>A rule for calculating an estimate of a given quantity based on observed data.</li>
<li>The quantity of interest.</li>
<li>The result.</li>
<li>Unknown numbers that determine a statistical model.</li>
</ol></li>
<li><span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989, 298</a>)</span> mentions ‘a randomized play the winner design’. What is it?</li>
<li><span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989, 299</a>)</span> mentions ‘adaptive randomization’. What is it, in your own words?</li>
<li><span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989, 299</a>)</span> mentions ‘randomized-consent’. He continues that it was ‘attractive in this setting because a standard approach to informed consent would require that parents of infants near death be approached to give informed consent for an invasive surgical procedure that would then, in some instances, not be administered. Those familiar with the agonizing experience of having a child in a neonatal intensive care unit can appreciate that the process of obtaining informed consent would be both frightening and stressful to parents’. To what extent do you agree with this position, especially given, as Ware (1989), p.&nbsp;305, mentions ‘the need to withhold information about the study from parents of infants receiving CMT’?</li>
<li><span class="citation" data-cites="ware1989investigating">Ware (<a href="references.html#ref-ware1989investigating" role="doc-biblioref">1989, 300</a>)</span> mentions ‘equipoise’. In your own words, please define and discuss it, using an example from your own experience.</li>
</ol>
</section>
<section id="tutorial" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="tutorial"><span class="header-section-number">10.4.2</span> Tutorial</h3>
<p>Please build a website using <code>postcards</code> <span class="citation" data-cites="citepostcards">(<a href="references.html#ref-citepostcards" role="doc-biblioref">Kross 2021</a>)</span>. Add Google Analytics. Deploy it using Netlify. Change some aspect of the website, add a different tracker, and push it to a new branch. Then use Netlify to conduct an A/B test. Write a one-to-two page paper about what you did and what you found.</p>
</section>
<section id="paper" class="level3" data-number="10.4.3">
<h3 data-number="10.4.3" class="anchored" data-anchor-id="paper"><span class="header-section-number">10.4.3</span> Paper</h3>
<p>At about this point, Paper Three (Appendix @ref(paper-three)) would be appropriate.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-tuskegeeandthehealthofblackmen" class="csl-entry" role="doc-biblioentry">
Alsan, Marcella, and Marianne Wanamaker. 2018. <span>“Tuskegee and the Health of Black Men.”</span> <em>The Quarterly Journal of Economics</em> 133 (1): 407–55.
</div>
<div id="ref-athey2017state" class="csl-entry" role="doc-biblioentry">
Athey, Susan, and Guido W Imbens. 2017. <span>“The State of Applied Econometrics: Causality and Policy Evaluation.”</span> <em>Journal of Economic Perspectives</em> 31 (2): 3–32.
</div>
<div id="ref-berry1989investigating" class="csl-entry" role="doc-biblioentry">
Berry, Donald A. 1989. <span>“[Investigating Therapies of Potentially Great Benefit: ECMO]: Comment: Ethics and ECMO.”</span> <em>Statistical Science</em> 4 (4): 306–10.
</div>
<div id="ref-brandt1978racism" class="csl-entry" role="doc-biblioentry">
Brandt, Allan M. 1978. <span>“Racism and Research: The Case of the Tuskegee Syphilis Study.”</span> <em>Hastings Center Report</em>, 21–29.
</div>
<div id="ref-randhealth" class="csl-entry" role="doc-biblioentry">
Brook, Robert H, John E Ware, William H Rogers, Emmett B Keeler, Allyson Ross Davies, Cathy D Sherbourne, George A Goldberg, Kathleen N Lohr, Patricia Camp, and Joseph P Newhouse. 1984. <span>“The Effect of Coinsurance on the Health of Adults: Results from the RAND Health Insurance Experiment.”</span>
</div>
<div id="ref-Cunningham2021" class="csl-entry" role="doc-biblioentry">
Cunningham, Scott. 2021. <em>Causal Inference: The Mixtape</em>. Yale Press.
</div>
<div id="ref-finkelstein2012oregon" class="csl-entry" role="doc-biblioentry">
Finkelstein, Amy, Sarah Taubman, Bill Wright, Mira Bernstein, Jonathan Gruber, Joseph P Newhouse, Heidi Allen, Katherine Baicker, and Oregon Health Study Group. 2012. <span>“The Oregon Health Insurance Experiment: Evidence from the First Year.”</span> <em>The Quarterly Journal of Economics</em> 127 (3): 1057–1106.
</div>
<div id="ref-fisherdesignofexperiments" class="csl-entry" role="doc-biblioentry">
Fisher, Ronald. 1935. <em>The Design of Experiments</em>. Oliver; Boyd.
</div>
<div id="ref-aboutupworthy" class="csl-entry" role="doc-biblioentry">
Fitts, Alexis Sobel. 2014. <span>“The King of Content: How Upworthy Aims to Alter the Web, and Could End up Altering the World.”</span> <em>Columbia Journalism Review</em>. <a href="https://archives.cjr.org/feature/the\%5Fking\%5Fof\%5Fcontent.php">https://archives.cjr.org/feature/the\%5Fking\%5Fof\%5Fcontent.php</a>.
</div>
<div id="ref-fry2020big" class="csl-entry" role="doc-biblioentry">
Fry, Hannah. 2020. <span>“Big Tech Is Testing You.”</span> <em>The New Yorker</em>, 61–65.
</div>
<div id="ref-gertler2016impact" class="csl-entry" role="doc-biblioentry">
Gertler, Paul J, Sebastian Martinez, Patrick Premand, Laura B Rawlings, and Christel MJ Vermeersch. 2016. <em>Impact Evaluation in Practice</em>. The World Bank.
</div>
<div id="ref-holland1986statistics" class="csl-entry" role="doc-biblioentry">
Holland, Paul W. 1986. <span>“Statistics and Causal Inference.”</span> <em>Journal of the American Statistical Association</em> 81 (396): 945–60.
</div>
<div id="ref-kohavi" class="csl-entry" role="doc-biblioentry">
Kohavi, Ron, Diane Tang, and Ya Xu. 2020. <em>Trustworthy Online Controlled Experiments: A Practical Guide to a/b Testing</em>. Cambridge University Press.
</div>
<div id="ref-citepostcards" class="csl-entry" role="doc-biblioentry">
Kross, Sean. 2021. <em>Postcards: Create Beautiful, Simple Personal Websites</em>. <a href="https://CRAN.R-project.org/package=postcards">https://CRAN.R-project.org/package=postcards</a>.
</div>
<div id="ref-upworthy" class="csl-entry" role="doc-biblioentry">
Matias, J. Nathan, Kevin Munger, Marianne Aubin Le Quere, and Charles Ebersole. 2019. <span>“The Upworthy Research Archive.”</span> <a href="https://upworthy.natematias.com">https://upworthy.natematias.com</a>.
</div>
<div id="ref-obermeyer2019dissecting" class="csl-entry" role="doc-biblioentry">
Obermeyer, Ziad, Brian Powers, Christine Vogeli, and Sendhil Mullainathan. 2019. <span>“Dissecting Racial Bias in an Algorithm Used to Manage the Health of Populations.”</span> <em>Science</em> 366 (6464): 447–53.
</div>
<div id="ref-Salganik2018" class="csl-entry" role="doc-biblioentry">
Salganik, Matthew. 2018. <em>Bit by Bit: Social Research in the Digital Age</em>. Princeton University Press.
</div>
<div id="ref-stolberg2006inventing" class="csl-entry" role="doc-biblioentry">
Stolberg, Michael. 2006. <span>“Inventing the Randomized Double-Blind Trial: The Nuremberg Salt Test of 1835.”</span> <em>Journal of the Royal Society of Medicine</em> 99 (12): 642–43.
</div>
<div id="ref-taddy2019" class="csl-entry" role="doc-biblioentry">
Taddy, Matt. 2019. <em>Business Data Science</em>. McGraw Hill.
</div>
<div id="ref-ware1989investigating" class="csl-entry" role="doc-biblioentry">
Ware, James H. 1989. <span>“Investigating Therapies of Potentially Great Benefit: ECMO.”</span> <em>Statistical Science</em> 4 (4): 298–306.
</div>
<div id="ref-wei1978randomized" class="csl-entry" role="doc-biblioentry">
Wei, LJ, and S Durham. 1978. <span>“The Randomized Play-the-Winner Rule in Medical Trials.”</span> <em>Journal of the American Statistical Association</em> 73 (364): 840–43.
</div>
<div id="ref-tidyverse" class="csl-entry" role="doc-biblioentry">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al. 2019. <span>“Welcome to the <span class="nocase">tidyverse</span>.”</span> <em>Journal of Open Source Software</em> 4 (43): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./09-gather.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Gather data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./11-clean_and_prepare.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Clean and prepare</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>