<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.486">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Telling Stories with Data - 14&nbsp; It’s Just A Linear Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./15-causality_from_obs.html" rel="next">
<link href="./13-eda.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">It’s Just A Linear Model</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Telling Stories with Data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/RohanAlexander/telling_stories/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-author.html" class="sidebar-item-text sidebar-link">About the author</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Foundations</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Telling stories with data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-drinking_from_a_fire_hose.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Drinking from a fire hose</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-r_essentials.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R essentials</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reproducible workflows</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Communication</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-on_writing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">On writing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-static_communication.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Static communication</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-interactive_communication.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Interactive communication</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Acquisition</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-farm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Farm data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-gather.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Gather data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-hunt.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hunt data</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Preparation</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-clean_and_prepare.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Clean and prepare</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-store_and_share.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Store and share</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Modelling</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-eda.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Exploratory data analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-ijalm.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">It’s Just A Linear Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-causality_from_obs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Causality from observational data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-mrp.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Multilevel regression with post-stratification</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-text.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Text as data</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Enrichment</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-deploy.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Deploying models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-efficiency.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Efficiency</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-concluding.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Concluding remarks</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">Appendices</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-assessment.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Papers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-datasets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Datasets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98-cocktails.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Cocktails</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"> <span class="header-section-number">14.1</span> Introduction</a></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression"> <span class="header-section-number">14.2</span> Simple linear regression</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression"> <span class="header-section-number">14.3</span> Multiple linear regression</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"> <span class="header-section-number">14.4</span> Logistic regression</a></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression"> <span class="header-section-number">14.5</span> Poisson regression</a></li>
  <li><a href="#exercises-and-tutorial" id="toc-exercises-and-tutorial" class="nav-link" data-scroll-target="#exercises-and-tutorial"> <span class="header-section-number">14.6</span> Exercises and tutorial</a>
  <ul class="collapse">
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"> <span class="header-section-number">14.6.1</span> Exercises</a></li>
  <li><a href="#tutorial" id="toc-tutorial" class="nav-link" data-scroll-target="#tutorial"> <span class="header-section-number">14.6.2</span> Tutorial</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/RohanAlexander/telling_stories/edit/main/14-ijalm.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-its-just-a-linear-model" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">It’s Just A Linear Model</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p><strong>Required material</strong></p>
<ul>
<li>Read <em>An Introduction to Statistical Learning with Applications in R</em>, Chapters 3 ‘Linear Regression’, and 4 ‘Classification’, <span class="citation" data-cites="islr">(<a href="references.html#ref-islr" role="doc-biblioref">James et al. 2017</a>)</span></li>
<li>Read <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>, Chapters 3 ‘Linear regression: the basics’, 4 ‘Linear regression: before and after fitting the model’, 5 ‘Logistic regression’, and 6 ‘Generalized linear models’, <span class="citation" data-cites="gelmanandhill">(<a href="references.html#ref-gelmanandhill" role="doc-biblioref">Gelman and Hill 2007</a>)</span></li>
<li>Read <em>Why most published research findings are false</em>, <span class="citation" data-cites="ioannidis2005most">(<a href="references.html#ref-ioannidis2005most" role="doc-biblioref">Ioannidis 2005</a>)</span></li>
</ul>
<!-- - Pavlik, Kaylin, 2018, 'Exploring the Relationship Between Dog Names and Breeds', https://www.kaylinpavlik.com/dog-names-tfidf/. -->
<!-- - Pavlik, Kaylin, 2019, 'Understanding + classifying genres using Spotify audio features', https://www.kaylinpavlik.com/classifying-songs-genres/. -->
<!-- - Silge, Julia, 2019, 'Modeling salary and gender in the tech industry', https://juliasilge.com/blog/salary-gender/. -->
<!-- - Silge, Julia, 2019, 'Opioid prescribing habits in Texas', https://juliasilge.com/blog/texas-opioids/. -->
<!-- - Silge, Julia, 2019, 'Tidymodels', https://juliasilge.com/blog/intro-tidymodels/. -->
<!-- - Silge, Julia, 2020, '#TidyTuesday hotel bookings and recipes', https://juliasilge.com/blog/hotels-recipes/. -->
<!-- - Silge, Julia, 2020, 'Hyperparameter tuning and #TidyTuesday food consumption', https://juliasilge.com/blog/food-hyperparameter-tune/. -->
<!-- - Taddy, Matt, 2019, *Business Data Science*, Chapters 2 and 4. -->
<!-- - Wasserstein, Ronald L. and Nicole A. Lazar, 2016, 'The ASA Statement on p-Values: Context, Process, and Purpose', *The American Statistician*, 70:2, 129-133, DOI: 10.1080/00031305.2016.1154108. -->
<!-- https://rviews.rstudio.com/2020/03/10/comparing-machine-learning-algorithms-for-predicting-clothing-classes-part-3/ -->
<!-- https://juliasilge.com/blog/tuition-resampling/ -->
<p><strong>Key concepts and skills</strong></p>
<ul>
<li>Simple and multiple linear regression.</li>
<li>Logistic and Poisson regression.</li>
<li>The key role of uncertainty.</li>
<li>Threats to validity of inference.</li>
<li>Overfitting.</li>
</ul>
<p><strong>Key packages and functions</strong></p>
<ul>
<li><code>broom</code> <span class="citation" data-cites="broom">(<a href="references.html#ref-broom" role="doc-biblioref">Robinson, Hayes, and Couch 2021</a>)</span></li>
<li><code>modelsummary</code> <span class="citation" data-cites="citemodelsummary">(<a href="references.html#ref-citemodelsummary" role="doc-biblioref">Arel-Bundock 2021</a>)</span></li>
<li><code>rstanarm</code> <span class="citation" data-cites="citerstanarm">(<a href="references.html#ref-citerstanarm" role="doc-biblioref">Goodrich et al. 2020</a>)</span></li>
<li><code>tidymodels</code> <span class="citation" data-cites="citeTidymodels">(<a href="references.html#ref-citeTidymodels" role="doc-biblioref">Kuhn and Wickham 2020</a>)</span></li>
<li><code>tidyverse</code> <span class="citation" data-cites="tidyverse">(<a href="references.html#ref-tidyverse" role="doc-biblioref">Wickham et al. 2019</a>)</span></li>
</ul>
<p><strong>Key functions</strong></p>
<ul>
<li><code>broom::augment()</code></li>
<li><code>broom::glance()</code></li>
<li><code>broom::tidy()</code></li>
<li><code>glm()</code></li>
<li><code>lm()</code></li>
<li><code>modelsummary::modelsummary()</code></li>
<li><code>parsnip::fit()</code></li>
<li><code>parsnip::linear_reg()</code></li>
<li><code>parsnip::logistic_reg()</code></li>
<li><code>parsnip::set_engine()</code></li>
<li><code>poissonreg::poisson_reg()</code></li>
<li><code>rnorm()</code></li>
<li><code>rpois()</code></li>
<li><code>rsample::initial_split()</code></li>
<li><code>rsample::testing()</code></li>
<li><code>rsample::training()</code></li>
<li><code>sample()</code></li>
<li><code>set.seed()</code></li>
<li><code>summary()</code></li>
</ul>
<section id="introduction" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">14.1</span> Introduction</h2>
<p>Linear models have been around for a long time. For instance, speaking about the development of least squares, which is one way to fit linear models, in the 1700s, <span class="citation" data-cites="stigler">Stigler (<a href="references.html#ref-stigler" role="doc-biblioref">1986, 16</a>)</span> describes how it was associated with foundational problems in astronomy, such as determining the motion of the moon and reconciling the non-periodic motion of Jupiter and Saturn. The fundamental issue at the time with least squares was that of hesitancy to combine different observations. Astronomers were early to develop a comfort with doing this because they had typically gathered their observations themselves and knew that the conditions of the data gathering were similar, even though the value of the observation was different. It took longer for social scientists to become comfortable with linear models, possibly because they were hesitant to group together data they worried was not alike. In this sense, astronomers had an advantage because they could compare their predictions with what actually happened whereas this was more difficult for social scientists <span class="citation" data-cites="stigler">(<a href="references.html#ref-stigler" role="doc-biblioref">Stigler 1986, 163</a>)</span>.</p>
<p>Galton and others of his generation, some of whom were eugenicists, used linear regression in earnest in the late 1800s and early 1900s. Binary outcomes quickly became of interest and needed special treatment, leading to the development and wide adaption of logistic regression and similar methods in the mid-1900s <span class="citation" data-cites="cramer2002origins">(<a href="references.html#ref-cramer2002origins" role="doc-biblioref">Cramer 2002</a>)</span>. The generalized linear model framework came into being, in a formal sense, in the 1970s with <span class="citation" data-cites="nelder1972generalized">Nelder and Wedderburn (<a href="references.html#ref-nelder1972generalized" role="doc-biblioref">1972</a>)</span> who brought this all together. Generalized linear models (GLM) broaden the types of outcomes that are allowed. We still model outcomes as a linear function, but we are not constrained to an outcome that is normally distributed. The outcome can be anything in the exponential family, and popular choices include the logistic distribution, and the Poisson distribution. A further generalization of GLMs is generalized additive models where we broaden the structure of the explanatory side. We still explain the dependent variable as an additive function of various bits and pieces, but those bits and pieces can be functions. This framework, in this way, came about in the 1990s, with <span class="citation" data-cites="hastie1990generalized">Hastie and Tibshirani (<a href="references.html#ref-hastie1990generalized" role="doc-biblioref">1990</a>)</span>.</p>
<p>It is important to recognize that when we build models, we are not discovering ‘the truth’. We are using the model to help us explore and understand the data that we have. There is no one best model, there are just useful models that help us learn something about the data that we have and hence, hopefully, something about the world from which the data were generated. When we use models, we are trying to understand the world, but there are enormous constraints on the perspective we bring to this. It is silly to expect one model to be universal. Further, we should not just blindly throw data into a regression model and hope that it will sort it out. ‘Regression will not sort it out. Regression is indeed an oracle, but a cruel one. It speaks in riddles and delights in punishing us for asking bad questions’ <span class="citation" data-cites="citemcelreath">(<a href="references.html#ref-citemcelreath" role="doc-biblioref">McElreath 2020, 162</a>)</span>.</p>
<p>We use models to understand the world. We poke, push, and test them. We build them and rejoice in their beauty, and then seek to understand their limits and ultimately destroy them. It is this process that is important, it is this process that allows us to better understand the world; not the outcome. When we build models, we need to keep in mind both the world of the model and the broader world that we want to be able to speak about. To what extent does a model trained on the experiences of straight, cis, men, speak to the world as it is? It is not worthless, but it is also not unimpeachable. To what extent does the model teach us about the data that we have? To what extent do the data that we have reflect the world about which we would like to draw conclusions? We need to keep such questions front of mind.</p>
<p>Much of statistics was developed without concern for broader implications. And that was reasonable because it was developed for situations such as astronomy and agriculture. Folks were literally able to randomize the order of fields and planting because they literally worked at agricultural stations. But many of the subsequent applications in the twentieth and twenty-first centuries, do not have those properties. Statistical science is often taught as though it proceeds through some idealized process where a hypothesis appears, is tested, and is either confirmed or not. But that is not what happens. We react to incentives. We dabble, guess, and test, and then follow our intuition, backfilling as we need. All of this is fine. But it is not a world in which a traditional null hypothesis holds completely, which means concepts such as p-values and power lose some of their meaning. While we need to understand the ‘old world’, we also need to be sophisticated enough to know when we need to move away from it. We can appreciate the beauty and ingenuity of a Ford Model T, at the same time recognizing we could not use it to win Le Mans.</p>
<p>In this chapter we begin with simple linear regression, and then move to multiple linear regression, the difference being the number of explanatory variables that we allow. We then consider logistic and Poisson regression. We consider three approaches for each of these: base R, which is useful when we want to quickly use the models in EDA; <code>tidymodels</code> <span class="citation" data-cites="citeTidymodels">(<a href="references.html#ref-citeTidymodels" role="doc-biblioref">Kuhn and Wickham 2020</a>)</span> which is useful when we are interested in forecasting; and <code>rstanarm</code> <span class="citation" data-cites="citerstanarm">(<a href="references.html#ref-citerstanarm" role="doc-biblioref">Goodrich et al. 2020</a>)</span> when we are interested in understanding. Regardless of the approach we use, the important thing to remember is that modelling in this way is just fancy averaging. The chapter is named for a quote by Daniela Witten, Professor, University of Washington, who identifies how far we can get with linear models and the huge extent to which they underpin statistics.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Shoulders of giants
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dr Daniela Witten</p>
</div>
</div>
</section>
<section id="simple-linear-regression" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="simple-linear-regression"><span class="header-section-number">14.2</span> Simple linear regression</h2>
<p>When we are interested in the relationship between two continuous variables, say <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>, we can use simple linear regression. This is based on the Normal, also ‘Gaussian’, distribution. The shape of the Normal distribution is determined by two parameters, the mean <span class="math inline">\(\mu\)</span> and the standard deviation, <span class="math inline">\(\sigma\)</span>:</p>
<p><span class="math display">\[y = \frac{1}{\sqrt{2\pi\sigma}}e^{-\frac{1}{2}z^2},\]</span></p>
<p>where <span class="math inline">\(z = (x - \mu)/\sigma\)</span> is the difference between the mean, <span class="math inline">\(\mu\)</span>, and <span class="math inline">\(x\)</span> in terms of the standard deviation <span class="citation" data-cites="pitman">(<a href="references.html#ref-pitman" role="doc-biblioref">Pitman 1993, 94</a>)</span>.</p>
<p>As discussed in Chapter @ref(r-essentials), we use <code>rnorm()</code> to simulate data from the Normal distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>twenty_draws_from_normal_distribution <span class="ot">&lt;-</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">draws =</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">20</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>twenty_draws_from_normal_distribution</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 1
     draws
     &lt;dbl&gt;
 1 -0.360 
 2 -0.0406
 3 -1.78  
 4 -1.12  
 5 -1.00  
 6  1.78  
 7 -1.39  
 8 -0.497 
 9 -0.558 
10 -0.824 
11  1.67  
12 -0.682 
13  0.0652
14 -0.260 
15  0.329 
16 -0.437 
17 -0.323 
18  0.115 
19  0.842 
20  0.342 </code></pre>
</div>
</div>
<p>Here we specified <span class="math inline">\(n=20\)</span> draws from a Normal distribution with mean of 0 and standard deviation of 1. When we deal with real data, we will not know these parameters and we want to use our data to estimate them. We can estimate the mean, <span class="math inline">\(\bar{x}\)</span>, and standard deviation, <span class="math inline">\(\hat{\sigma}_x\)</span>, with the following estimators:</p>
<p><span class="math display">\[
\begin{aligned}
\bar{x} &amp;= \frac{1}{n} \times \sum_{i = 1}^{n}x_i\\
\hat{\sigma}_{x} &amp;= \sqrt{\frac{1}{n} \times \sum_{i = 1}^{n}\left(x_i - \bar{x}\right)^2}
\end{aligned}
\]</span></p>
<p>If <span class="math inline">\(\hat{\sigma}_x\)</span> is the standard deviation, then a standard error of an estimate, say, <span class="math inline">\(\bar{x}\)</span> is:</p>
<p><span class="math display">\[\mbox{SE}(\bar{x})^2 = \frac{\sigma^2}{n}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>estimated_mean <span class="ot">&lt;-</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(twenty_draws_from_normal_distribution<span class="sc">$</span>draws) <span class="sc">/</span> <span class="fu">nrow</span>(twenty_draws_from_normal_distribution)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>estimated_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2069253</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>estimated_mean <span class="ot">&lt;-</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  twenty_draws_from_normal_distribution <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">draws_diff_square =</span> (draws <span class="sc">-</span> estimated_mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>estimated_standard_deviation <span class="ot">&lt;-</span> </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(estimated_mean<span class="sc">$</span>draws_diff_square) <span class="sc">/</span> <span class="fu">nrow</span>(twenty_draws_from_normal_distribution)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>estimated_standard_deviation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8832841</code></pre>
</div>
</div>
<p>We should not be worried that our estimates are slightly off. It will typically take a larger number of draws before we get the expected shape, and our estimated parameters get close to the actual parameters, but it will happen (<a href="#fig-normaldistributiontakingshape">Figure&nbsp;<span>14.1</span></a>). <span class="citation" data-cites="wasserman">Wasserman (<a href="references.html#ref-wasserman" role="doc-biblioref">2005, 76</a>)</span> describes our certainty of this, which is due to the Law of Large Numbers, as ‘a crowning achievement in probability’.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">number_of_draws =</span> <span class="fu">c</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep.int</span>(<span class="at">x =</span> <span class="st">"2 draws"</span>, <span class="at">times =</span> <span class="dv">2</span>),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep.int</span>(<span class="at">x =</span> <span class="st">"5 draws"</span>, <span class="at">times =</span> <span class="dv">5</span>),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep.int</span>(<span class="at">x =</span> <span class="st">"10 draws"</span>, <span class="at">times =</span> <span class="dv">10</span>),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep.int</span>(<span class="at">x =</span> <span class="st">"50 draws"</span>, <span class="at">times =</span> <span class="dv">50</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep.int</span>(<span class="at">x =</span> <span class="st">"100 draws"</span>, <span class="at">times =</span> <span class="dv">100</span>),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep.int</span>(<span class="at">x =</span> <span class="st">"500 draws"</span>, <span class="at">times =</span> <span class="dv">500</span>),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep.int</span>(<span class="at">x =</span> <span class="st">"1,000 draws"</span>, <span class="at">times =</span> <span class="dv">1000</span>),</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep.int</span>(<span class="at">x =</span> <span class="st">"10,000 draws"</span>, <span class="at">times =</span> <span class="dv">10000</span>),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep.int</span>(<span class="at">x =</span> <span class="st">"100,000 draws"</span>, <span class="at">times =</span> <span class="dv">100000</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">draws =</span> <span class="fu">c</span>(</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">2</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">5</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">500</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">10000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">100000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">number_of_draws =</span> <span class="fu">as_factor</span>(number_of_draws)) <span class="sc">|&gt;</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> draws)) <span class="sc">+</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(number_of_draws),</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>             <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Draw'</span>,</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">'Density'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-normaldistributiontakingshape" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/fig-normaldistributiontakingshape-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 14.1: The Normal distribution takes its familiar shape as the number of draws increases</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>When we use simple linear regression, we assume that our relationship is characterized by the variables and the parameters. If we have two variables, <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>, then we could characterize a linear relationship between these as:</p>
<p><span class="math display">\[Y \approx \beta_0 + \beta_1 X.\]</span></p>
<p>There are two coefficients, also ‘parameters’: the ‘intercept’, <span class="math inline">\(\beta_0\)</span>, and the ‘slope’, <span class="math inline">\(\beta_1\)</span>. We are saying that <span class="math inline">\(Y\)</span> will have some value, <span class="math inline">\(\beta_0\)</span>, even when <span class="math inline">\(X\)</span> is 0, and that <span class="math inline">\(Y\)</span> will change by <span class="math inline">\(\beta_1\)</span> units for every one unit change in <span class="math inline">\(X\)</span>. The language that we use is that ‘X is being regressed on Y’. We may then take this relationship to the data that we have, in order to estimate these coefficients, for the particular data that we have.</p>
<p>To make this example concrete, we will simulate some data and then discuss it in that context. For instance, we could consider the time it takes someone to run five kilometers, compared with the time it takes them to run a marathon (<a href="#fig-fivekmvsmarathon">Figure&nbsp;<span>14.2</span></a>). We impute a relationship of 8.4, as that is roughly the ratio between the distance of a marathon and a five-kilometer race.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>number_of_observations <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>expected_relationship <span class="ot">&lt;-</span> <span class="fl">8.4</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>simulated_running_data <span class="ot">&lt;-</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">five_km_time =</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>           <span class="fu">runif</span>(<span class="at">n =</span> number_of_observations, </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">min =</span> <span class="dv">15</span>, </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">max =</span> <span class="dv">30</span>),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">noise =</span> <span class="fu">rnorm</span>(number_of_observations, <span class="dv">0</span>, <span class="dv">20</span>),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">marathon_time =</span> five_km_time <span class="sc">*</span> expected_relationship <span class="sc">+</span> noise</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">|&gt;</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">five_km_time =</span> <span class="fu">round</span>(five_km_time, <span class="at">digits =</span> <span class="dv">1</span>),</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">marathon_time =</span> <span class="fu">round</span>(marathon_time, <span class="at">digits =</span> <span class="dv">1</span>)) <span class="sc">|&gt;</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>noise)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>simulated_running_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 2
   five_km_time marathon_time
          &lt;dbl&gt;         &lt;dbl&gt;
 1         20.4          152.
 2         16.8          134.
 3         22.3          198.
 4         19.7          166.
 5         15.6          163.
 6         21.1          168.
 7         17            131.
 8         18.6          150.
 9         17.4          158.
10         17.8          147.
# … with 90 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> five_km_time, <span class="at">y =</span> marathon_time)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Five-kilometer time (minutes)"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Marathon time (minutes)"</span>) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fivekmvsmarathon" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/fig-fivekmvsmarathon-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 14.2: Simulated data of the relationship between the time to run five kilometers and a marathon</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In this simulated example, we know what <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are. But our challenge is to see if we can use only the data, and simple linear regression, to recover them. That is, can we use <span class="math inline">\(x\)</span>, which is the five-kilometer time, to produce estimates of <span class="math inline">\(y\)</span>, which is the marathon time, and which we will put a hat on to denote our estimate:</p>
<p><span class="math display">\[\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x.\]</span></p>
<p>The hats are used to indicate that these are estimated values.</p>
<p>This involves estimating values for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, and again, our estimates will be denoted by a hat on them. But how should we estimate these coefficients? Even if we impose a linear relationship there are many options, because a large number of straight lines could be drawn. But some of those lines would fit the data better than others.</p>
<p>One way we may define a line as being ‘better’ than another, is if it is as close as possible to each of the <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> combinations that we know. There are a lot of candidates for how we define ‘as close as possible’, but one is to minimize the residual sum of squares. To do this we produce estimates for <span class="math inline">\(\hat{y}\)</span> based on some guesses of <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span>, given the <span class="math inline">\(x\)</span>. We then work out how ‘wrong’, for every point <span class="math inline">\(i\)</span>, we were:</p>
<p><span class="math display">\[e_i = y_i - \hat{y}_i.\]</span></p>
<p>To compute the residual sum of squares (RSS), we sum across all the points, taking the square to account for negative differences:</p>
<p><span class="math display">\[\mbox{RSS} = e^2_1+ e^2_2 +\dots + e^2_n.\]</span></p>
<p>This results in one ‘linear best-fit’ line (<a href="#fig-fivekmvsmarathonwithbestfit">Figure&nbsp;<span>14.3</span></a>), but it is worth thinking about all the assumptions and decisions that it took to get us to this point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> five_km_time, <span class="at">y =</span> marathon_time)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>, </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> <span class="st">'y ~ x'</span>) <span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Five-kilometer time (minutes)"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Marathon time (minutes)"</span>) <span class="sc">+</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fivekmvsmarathonwithbestfit" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/fig-fivekmvsmarathonwithbestfit-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 14.3: Simulated data of the relationship between the time to run five kilometers and a marathon</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Underpinning our use of simple linear regression is a belief that there is some ‘true’ relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, that is:</p>
<p><span class="math display">\[Y = f(X) + \epsilon.\]</span></p>
<p>We are going to say that function, <span class="math inline">\(f()\)</span>, is linear, and so for simple linear regression:</p>
<p><span class="math display">\[\hat{Y} = \beta_0 + \beta_1 X + \epsilon.\]</span></p>
<p>There is some ‘true’ relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, but we do not know what it is. All we can do is use our sample of data to estimate it. But because our understanding depends on that sample, for every possible sample, we would get a slightly different relationship, as measured by the coefficients.</p>
<p>That <span class="math inline">\(\epsilon\)</span> is a measure of our error—what does the model not know? There is going to be plenty that the model does not know, but we hope the error does not depend on <span class="math inline">\(X\)</span>, and that the error is normally distributed.</p>
<p>We can conduct simple linear regression with <code>lm()</code> from base R. We specify the dependent variable first, then <code>~</code>, followed by the independent variables. Finally, we specify the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data_first_model <span class="ot">&lt;-</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(marathon_time <span class="sc">~</span> five_km_time, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> simulated_running_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To see the result of the regression, we can use <code>summary()</code> from base R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simulated_running_data_first_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = marathon_time ~ five_km_time, data = simulated_running_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-49.654  -9.278   0.781  12.606  56.898 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    8.2393     8.9550    0.92     0.36    
five_km_time   7.9407     0.4072   19.50   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.96 on 98 degrees of freedom
Multiple R-squared:  0.7951,    Adjusted R-squared:  0.793 
F-statistic: 380.3 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The first part of the result tells us the regression that we specified, then information about the residuals, and our estimated coefficients. And then finally some useful diagnostics.</p>
<p>The intercept is the marathon time that we would expect with a five-kilometer time of 0 minutes. Hopefully this example illustrates the need to carefully interpret the intercept coefficient! The coefficient on five-kilometer run time shows how we expect the marathon time to change if the five-kilometer run time changed by one unit. In this case it is about 8.4, which makes sense seeing as a marathon is roughly that many times longer than a five-kilometer run.</p>
<p>We use <code>augment()</code> from <code>broom</code> <span class="citation" data-cites="broom">(<a href="references.html#ref-broom" role="doc-biblioref">Robinson, Hayes, and Couch 2021</a>)</span> to add the fitted values and residuals to our original dataset. This allows us to plot the residuals (<span class="quarto-unresolved-ref">?fig-fivekmvsmarathonresids</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>simulated_running_data <span class="ot">&lt;-</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(simulated_running_data_first_model,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> simulated_running_data)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>simulated_running_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 8
   five_km_time marathon_time .fitted .resid   .hat .sigma   .cooksd .std.resid
          &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1         20.4          152.    170. -17.8  0.0108   17.0 0.00611       -1.06 
 2         16.8          134.    142.  -7.84 0.0232   17.0 0.00260       -0.468
 3         22.3          198.    185.  13.1  0.0103   17.0 0.00312        0.775
 4         19.7          166.    165.   1.83 0.0121   17.1 0.0000718      0.108
 5         15.6          163.    132.  31.3  0.0307   16.7 0.0556         1.87 
 6         21.1          168.    176.  -8.09 0.0101   17.0 0.00118       -0.479
 7         17            131.    143. -11.8  0.0222   17.0 0.00564       -0.705
 8         18.6          150.    156.  -6.04 0.0152   17.0 0.000990      -0.359
 9         17.4          158.    146.  11.1  0.0201   17.0 0.00448        0.661
10         17.8          147.    150.  -2.68 0.0183   17.0 0.000238      -0.160
# … with 90 more rows</code></pre>
</div>
</div>
<div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(simulated_running_data, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> .resid)) <span class="sc">+</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Number of occurrences"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Residuals"</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(simulated_running_data, </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> five_km_time, <span class="at">y =</span> .resid)) <span class="sc">+</span> </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">color =</span> <span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Five-kilometer time (minutes)"</span>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(simulated_running_data, </span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> marathon_time, .fitted)) <span class="sc">+</span> </span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Estimated marathon time"</span>,</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Actual marathon time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-fivekmvsmarathonresids-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/fig-fivekmvsmarathonresids-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 14.4: Residuals from the simple linear regression with simulated data on the time someone takes to run five kilometers and a marathon</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-fivekmvsmarathonresids-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/fig-fivekmvsmarathonresids-2.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 14.5: Residuals from the simple linear regression with simulated data on the time someone takes to run five kilometers and a marathon</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-fivekmvsmarathonresids-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/fig-fivekmvsmarathonresids-3.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 14.6: Residuals from the simple linear regression with simulated data on the time someone takes to run five kilometers and a marathon</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>We want our estimate to be unbiased. When we say our estimate is unbiased, we are trying to say that even though with some sample our estimate might be too high, and with another sample our estimate might be too low, eventually if we have a lot of data then our estimate would be the same as the population. An estimator is unbiased if it does not systematically over- or under-estimate <span class="citation" data-cites="islr">(<a href="references.html#ref-islr" role="doc-biblioref">James et al. 2017, 65</a>)</span>.</p>
<p>But we want to try to speak to the ‘true’ relationship, so we need to try to capture how much we think our understanding depends on the particular sample that we have to analyze. And this is where standard error comes in. It tells us how off our estimate is compared with the actual (<a href="#fig-fivekmvsmarathonses">Figure&nbsp;<span>14.7</span></a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data <span class="sc">|&gt;</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> five_km_time, <span class="at">y =</span> marathon_time)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">TRUE</span>, </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> <span class="st">'y ~ x'</span>) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Five-kilometer time (minutes)"</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Marathon time (minutes)"</span>) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fivekmvsmarathonses" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/fig-fivekmvsmarathonses-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 14.7: Simple linear regression with simulated data on the time someone takes to run five kilometers and a marathon, along with standard errors</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>From standard errors, we can compute a confidence interval. A 95 per cent confidence interval is a range, such that there is roughly a 0.95 probability that the interval happens to contain the population parameter, which is typically unknown. The lower end of this range is: <span class="math inline">\(\hat{\beta_1} - 2 \times \mbox{SE}\left(\hat{\beta_1}\right)\)</span> and the upper end of this range is: <span class="math inline">\(\hat{\beta_1} + 2 \times \mbox{SE}\left(\hat{\beta_1}\right)\)</span>.</p>
<p>Now that we have a range, for which we can say there is a roughly 95 per cent probability that range contains the true population parameter, we could test claims. For instance, we could claim that there is no relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, i.e.&nbsp;<span class="math inline">\(\beta_1 = 0\)</span>, as an alternative to a claim that there is some relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, i.e.&nbsp;<span class="math inline">\(\beta_1 \neq 0\)</span>.</p>
<p>In the same way that in <a href="10-hunt.html"><span>Chapter&nbsp;10</span></a> we needed to decide how much evidence it would take to convince us that our tea taster could distinguish whether milk or tea had been added first, we need to decide whether our estimate of <span class="math inline">\(\beta_1\)</span>, which is <span class="math inline">\(\hat{\beta}_1\)</span>, is ‘far enough’ away from zero for us to be comfortable claiming that <span class="math inline">\(\beta_1 \neq 0\)</span>. How far is ‘far enough’? If we were very confident in our estimate of <span class="math inline">\(\beta_1\)</span> then it would not have to be far, but if we were not then it would have to be substantial. The standard error of <span class="math inline">\(\hat{\beta}_1\)</span> does an awful lot of work here in accounting for a variety of factors, only some of which it can actually account for.</p>
<p>We compare this standard error with <span class="math inline">\(\hat{\beta}_1\)</span> to get the t-statistic:</p>
<p><span class="math display">\[t = \frac{\hat{\beta}_1 - 0}{\mbox{SE}(\hat{\beta}_1)}.\]</span></p>
<p>And we then compare our t-statistic to the t-distribution to compute the probability of getting this absolute t-statistic or a larger one, if it was actually the case that <span class="math inline">\(\beta_1 = 0\)</span>. This probability is the p-value. A smaller p-value means it is less likely that we would observe our data due to chance if there was not a relationship.</p>
<blockquote class="blockquote">
<p>Words! Mere words! How terrible they were! How clear, and vivid, and cruel! One could not escape from them. And yet what a subtle magic there was in them! They seemed to be able to give a plastic form to formless things, and to have a music of their own as sweet as that of viol or of lute. Mere words! Was there anything so real as words?</p>
<p><em>The Picture of Dorian Gray</em> <span class="citation" data-cites="wilde">(<a href="references.html#ref-wilde" role="doc-biblioref">Wilde 1891</a>)</span>.</p>
</blockquote>
<p>We will not make much use of p-values in this book because they are a specific and subtle concept. They are difficult to understand and easy to abuse. The main issue is that they embody, and assume correct, every assumption of the model, including everything that went into gathering and cleaning the data. While smaller p-values do imply the data are more unusual if all the assumptions were correct; when we consider the full data science workflow there are usually an awful lot of assumptions. And we do not get guidance from p-values about the reasonableness of specific assumptions <span class="citation" data-cites="greenland2016statistical">(<a href="references.html#ref-greenland2016statistical" role="doc-biblioref">Greenland et al. 2016, 339</a>)</span>. A p-value may reject a null hypothesis because the null hypothesis is actually false, but it may also be that some data were incorrectly gathered or prepared. We can only be sure that the p-value speaks to the hypothesis we are interested in testing, if all the other assumptions are correct. There is nothing inherently wrong about using p-values, but it is important to use them in sophisticated and thoughtful ways. <span class="citation" data-cites="coxtalks">D. Cox (<a href="references.html#ref-coxtalks" role="doc-biblioref">2018</a>)</span> provides a lovely discussion of what this requires.</p>
<p>One application where it is easy to see abuse of p-values is in power analysis. Power, in a statistical sense, refers to probability of rejecting a null hypothesis that is actually false. As power relates to hypothesis testing, it also related to sample size. There is often a worry that a study is ‘under-powered’, meaning there was not a large enough sample, but rarely a worry that, say, the data were inappropriately cleaned, even though we cannot distinguish between these based only on a p-value.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Shoulders of giants
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dr Nancy Reid is University Professor in the Department of Statistical Sciences at the University of Toronto. After obtaining a PhD in Statistics from Stanford University in 1979, she took a position as a postdoctoral fellow at Imperial College London. She was then appointed as assistant professor at the University of British Columbia in 1980, and then moved to the University of Toronto in 1986, where she was promoted to full professor in 1988 and served as department chair between 1997 and 2002 <span class="citation" data-cites="Staicu2017">(<a href="references.html#ref-Staicu2017" role="doc-biblioref">Staicu 2017</a>)</span>. Her research focuses on obtaining accurate inference in small-sample regimes and developing inferential procedures for complex models featuring intractable likelihoods. <span class="citation" data-cites="cox1987parameter">D. R. Cox and Reid (<a href="references.html#ref-cox1987parameter" role="doc-biblioref">1987</a>)</span> examines how re-parameterizing models can simplify inference, <span class="citation" data-cites="varin2011overview">Varin, Reid, and Firth (<a href="references.html#ref-varin2011overview" role="doc-biblioref">2011</a>)</span> surveys methods for approximating intractable likelihoods, and <span class="citation" data-cites="reid2003asymptotics">Reid (<a href="references.html#ref-reid2003asymptotics" role="doc-biblioref">2003</a>)</span> overviews inferential procedures in the small-sample regime. Dr Reid was awarded the 1992 COPSS Presidents’ Award, the 2016 Guy Medal in Silver, and the 2022 Guy Medal in Gold from the Royal Statistical Society.</p>
</div>
</div>
</section>
<section id="multiple-linear-regression" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="multiple-linear-regression"><span class="header-section-number">14.3</span> Multiple linear regression</h2>
<p>To this point we have just considered one explanatory variable. But we will usually have more than one. One approach would be to run separate regressions for each explanatory variable. But compared with separate linear regressions for each, adding more explanatory variables allows us to have a better understanding of the intercept and accounts for interaction. Often the results will be quite different.</p>
<p>We may also like to consider explanatory variables that do not have an inherent ordering. For instance: pregnant or not; day or night. When there are only two options then we can use a binary variable, which is considered either 0 or 1. If we have a column of character values that only has two values, such as: <code>c("Myles", "Ruth", "Ruth", "Myles", "Myles", "Ruth")</code>, then using this as an explanatory variable in the usual regression set up, would mean that it is treated as a binary variable. If there are more than two levels then we can use a combination of binary variables, where the ‘missing’ outcome (baseline) gets pushed into the intercept.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data <span class="ot">&lt;-</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  simulated_running_data <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">was_raining =</span> <span class="fu">sample</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> number_of_observations,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.8</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">|&gt;</span> </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(five_km_time, marathon_time, was_raining)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>simulated_running_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 3
   five_km_time marathon_time was_raining
          &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt;      
 1         20.4          152. No         
 2         16.8          134. No         
 3         22.3          198. No         
 4         19.7          166. No         
 5         15.6          163. No         
 6         21.1          168. No         
 7         17            131. No         
 8         18.6          150. No         
 9         17.4          158. No         
10         17.8          147. No         
# … with 90 more rows</code></pre>
</div>
</div>
<p>We can add additional explanatory variables to <code>lm()</code> with <code>+</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data_rain_model <span class="ot">&lt;-</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(marathon_time <span class="sc">~</span> five_km_time <span class="sc">+</span> was_raining,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> simulated_running_data)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simulated_running_data_rain_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = marathon_time ~ five_km_time + was_raining, data = simulated_running_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-49.150  -8.828   0.968  10.522  58.224 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      9.1030     9.0101   1.010    0.315    
five_km_time     7.8660     0.4154  18.934   &lt;2e-16 ***
was_rainingYes   4.1673     4.5048   0.925    0.357    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.98 on 97 degrees of freedom
Multiple R-squared:  0.7969,    Adjusted R-squared:  0.7927 
F-statistic: 190.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The result probably is not too surprising if we look at a plot of the data (<a href="#fig-fivekmvsmarathonbinary">Figure&nbsp;<span>14.8</span></a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> five_km_time, <span class="at">y =</span> marathon_time, <span class="at">color =</span> was_raining)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> <span class="st">'y ~ x'</span>) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Five-kilometer time (minutes)"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Marathon time (minutes)"</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Was raining"</span>) <span class="sc">+</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fivekmvsmarathonbinary" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/fig-fivekmvsmarathonbinary-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 14.8: Simple linear regression with simulated data on the time someone takes to run five kilometers and a marathon, with a binary variable for whether it was raining</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In addition to wanting to include additional explanatory variables, we may think that they are related with each another. For instance, if we were wanting to explain the amount of snowfall, then we may be interested in the humidity and the temperature, but those two variables may also interact. We can do this by using <code>*</code> instead of <code>+</code> when we specify the model. When we interact variables in this way, then we almost always need to include the individual variables as well and <code>lm()</code> will do this by default.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data <span class="ot">&lt;-</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  simulated_running_data <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">humidity =</span> <span class="fu">sample</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">"High"</span>, <span class="st">"Low"</span>),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> number_of_observations,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.8</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>simulated_running_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 4
   five_km_time marathon_time was_raining humidity
          &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;   
 1         20.4          152. No          Low     
 2         16.8          134. No          Low     
 3         22.3          198. No          Low     
 4         19.7          166. No          Low     
 5         15.6          163. No          Low     
 6         21.1          168. No          Low     
 7         17            131. No          Low     
 8         18.6          150. No          Low     
 9         17.4          158. No          High    
10         17.8          147. No          Low     
# … with 90 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data_rain_and_humidity_model <span class="ot">&lt;-</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(marathon_time <span class="sc">~</span> five_km_time <span class="sc">+</span> was_raining<span class="sc">*</span>humidity,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> simulated_running_data)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simulated_running_data_rain_and_humidity_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = marathon_time ~ five_km_time + was_raining * humidity, 
    data = simulated_running_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-48.904  -8.523   0.404  10.130  59.951 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 15.0595    10.3144   1.460    0.148    
five_km_time                 7.7313     0.4167  18.552   &lt;2e-16 ***
was_rainingYes              15.6008     9.6199   1.622    0.108    
humidityLow                 -3.7380     4.9569  -0.754    0.453    
was_rainingYes:humidityLow -14.5825    10.7410  -1.358    0.178    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.79 on 95 degrees of freedom
Multiple R-squared:  0.8054,    Adjusted R-squared:  0.7972 
F-statistic: 98.31 on 4 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There are a variety of threats to the validity of linear regression estimates, and aspects to think about. We need to address these when we use it, and usually four graphs and associated text are sufficient to assuage most of these. Aspects of concern include:</p>
<ol type="1">
<li>Linearity of explanatory variables. We are concerned with whether the independent variables enter in a linear way. Sometimes if we are worried that there might be a multiplicative relationship between the explanatory variables, rather than an additive one, then we may consider a logarithmic transform. We can usually be convinced there is enough linearity in our explanatory variables for our purposes by using graphs of the variables.</li>
<li>Independence of errors. We are concerned that the errors are not correlated. For instance, if we are interested in weather-related measurement such as average daily temperature, then we may find a pattern because the temperature on one day is likely similar to the temperature on another. We can be convinced that we have satisfied this condition by making graphs of the errors, such as <span class="quarto-unresolved-ref">?fig-fivekmvsmarathonresids</span>).</li>
<li>Homoscedasticity of errors. We are concerned that the errors are not becoming systematically larger or smaller throughout the sample. If that is happening, then we term it heteroscedasticity. Again, graphs of errors, such as <span class="quarto-unresolved-ref">?fig-fivekmvsmarathonresids</span>) are used to convince us of this.</li>
<li>Normality of errors. We are concerned that our errors are normally distributed when we are interested in making individual-level predictions.</li>
<li>Outliers and other high-impact observations. Finally, we might be worried that our results are being driven by a handful of observations. For instance, thinking back to Chapter @ref(static-communication) and Anscombe’s Quartet, we notice that linear regression estimates would be heavily influenced by the inclusion of one or two particular points. We can become comfortable with this by considering our analysis on various sub-sets</li>
</ol>
<p>Those aspects are statistical concerns and relate to whether the model is working. The most important threat to validity and hence the aspect that must be addressed at some length, is speaking to the fact that this model is appropriate to the circumstances and addresses the research question at hand.</p>
<p>To this point, we have just had a quick look at the regression results using <code>summary()</code>. A better approach is to use <code>modelsummary()</code> from <code>modelsummary</code> <span class="citation" data-cites="citemodelsummary">(<a href="references.html#ref-citemodelsummary" role="doc-biblioref">Arel-Bundock 2021</a>)</span> (<a href="#tbl-modelsummaryruntimes">Table&nbsp;<span>14.1</span></a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(<span class="fu">list</span>(simulated_running_data_first_model,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                  simulated_running_data_rain_model, </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                  simulated_running_data_rain_and_humidity_model),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">fmt =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-modelsummaryruntimes" class="anchored">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;"><caption>Table 14.1:  Explaining marathon time based on five-kilometer run times and weather features </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Model 1 </th>
   <th style="text-align:center;"> Model 2 </th>
   <th style="text-align:center;"> Model 3 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:center;"> 8.24 </td>
   <td style="text-align:center;"> 9.10 </td>
   <td style="text-align:center;"> 15.06 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;"> (8.96) </td>
   <td style="text-align:center;"> (9.01) </td>
   <td style="text-align:center;"> (10.31) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> five_km_time </td>
   <td style="text-align:center;"> 7.94 </td>
   <td style="text-align:center;"> 7.87 </td>
   <td style="text-align:center;"> 7.73 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;"> (0.41) </td>
   <td style="text-align:center;"> (0.42) </td>
   <td style="text-align:center;"> (0.42) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> was_rainingYes </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 4.17 </td>
   <td style="text-align:center;"> 15.60 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (4.50) </td>
   <td style="text-align:center;"> (9.62) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> humidityLow </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −3.74 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> (4.96) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> was_rainingYes × humidityLow </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> −14.58 </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px">  </td>
   <td style="text-align:center;box-shadow: 0px 1px"> (10.74) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Num.Obs. </td>
   <td style="text-align:center;"> 100 </td>
   <td style="text-align:center;"> 100 </td>
   <td style="text-align:center;"> 100 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 </td>
   <td style="text-align:center;"> 0.795 </td>
   <td style="text-align:center;"> 0.797 </td>
   <td style="text-align:center;"> 0.805 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 Adj. </td>
   <td style="text-align:center;"> 0.793 </td>
   <td style="text-align:center;"> 0.793 </td>
   <td style="text-align:center;"> 0.797 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AIC </td>
   <td style="text-align:center;"> 854.0 </td>
   <td style="text-align:center;"> 855.1 </td>
   <td style="text-align:center;"> 854.8 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BIC </td>
   <td style="text-align:center;"> 861.8 </td>
   <td style="text-align:center;"> 865.5 </td>
   <td style="text-align:center;"> 870.4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Log.Lik. </td>
   <td style="text-align:center;"> −423.993 </td>
   <td style="text-align:center;"> −423.554 </td>
   <td style="text-align:center;"> −421.405 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> F </td>
   <td style="text-align:center;"> 380.262 </td>
   <td style="text-align:center;"> 190.279 </td>
   <td style="text-align:center;"> 98.314 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>When we are focused on prediction, we will often want to fit many models. One way to do this is to copy and paste code many times. There is nothing wrong with that. And that is the way that most people get started. But we need an approach that:</p>
<ol type="1">
<li>scales more easily;</li>
<li>enables us to think carefully about over-fitting; and</li>
<li>adds model evaluation.</li>
</ol>
<p>The use of <code>tidymodels</code> <span class="citation" data-cites="citeTidymodels">(<a href="references.html#ref-citeTidymodels" role="doc-biblioref">Kuhn and Wickham 2020</a>)</span> satisfies these criteria by providing a coherent grammar that allows us to easily fit a variety of models. Like <code>tidyverse</code>, it is a package of packages.</p>
<p>As we are focused on prediction, we are worried about over-fitting our data, which would limit our ability to make claims about other datasets. One way to partially address this is to split our dataset into training and test datasets using <code>initial_split()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>simulated_running_data_split <span class="ot">&lt;-</span> </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">initial_split</span>(<span class="at">data =</span> simulated_running_data, </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">prop =</span> <span class="fl">0.80</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>simulated_running_data_split</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;Analysis/Assess/Total&gt;
&lt;80/20/100&gt;</code></pre>
</div>
</div>
<p>Having split the data, we then create the training and test datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data_train <span class="ot">&lt;-</span> <span class="fu">training</span>(simulated_running_data_split)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>simulated_running_data_train</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 4
   five_km_time marathon_time was_raining humidity
          &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;   
 1         17.4          158. No          High    
 2         23.8          205. No          High    
 3         23.4          198. Yes         Low     
 4         22.3          175  No          Low     
 5         19.3          158  No          Low     
 6         24.4          204. No          High    
 7         17            120  No          High    
 8         19.1          178. No          Low     
 9         22.3          198. No          Low     
10         20.6          166. No          Low     
# … with 70 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(simulated_running_data_split)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>simulated_running_data_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 4
   five_km_time marathon_time was_raining humidity
          &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;   
 1         17            131. No          Low     
 2         16.6          118. No          Low     
 3         19.6          164. No          Low     
 4         21.1          164. Yes         Low     
 5         21            180. No          Low     
 6         27.9          246. No          Low     
 7         23.7          198. No          High    
 8         16            143  No          Low     
 9         24.9          202. No          Low     
10         15.2          140. Yes         Low     
11         28.9          238. No          Low     
12         19.2          132  Yes         Low     
13         22            200. No          Low     
14         26.5          229  Yes         High    
15         25.3          222  Yes         High    
16         25.9          208. Yes         Low     
17         15.5          120  No          Low     
18         18            144. No          Low     
19         27.2          227. No          High    
20         20.8          201. No          Low     </code></pre>
</div>
</div>
<p>When we look at the training and test datasets, we can see that we have placed most of our dataset into the training dataset. We will use that to estimate the parameters of our model. We have kept a small amount of it back, and we will use that to evaluate our model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data_first_model_tidymodels <span class="ot">&lt;-</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="at">engine =</span> <span class="st">"lm"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(marathon_time <span class="sc">~</span> five_km_time <span class="sc">+</span> was_raining, </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> simulated_running_data_train</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>simulated_running_data_first_model_tidymodels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object

Fit time:  1ms 

Call:
stats::lm(formula = marathon_time ~ five_km_time + was_raining, 
    data = data)

Coefficients:
   (Intercept)    five_km_time  was_rainingYes  
        16.601           7.490           8.244  </code></pre>
</div>
</div>
<p>We will use <code>tidymodels</code> for forecasting. But when we are focused on inference, instead, we will use Bayesian approaches. To do this we use the probabilistic programming language ‘Stan’, and interface with it using <code>rstanarm</code> <span class="citation" data-cites="citerstanarm">(<a href="references.html#ref-citerstanarm" role="doc-biblioref">Goodrich et al. 2020</a>)</span>. We keep these separate, rather than adapting Bayesian approaches within <code>tidymodels</code>, because to this point the ecosystems have developed separately, and so the best books to go onto next are also separate.</p>
<p>In order to use Bayesian approaches we will need to specify a starting point, or prior. This is another reason for the workflow advocated in this book; the simulate stage leads directly to priors. We will also more thoroughly specify the model that we are interested in:</p>
<p><span class="math display">\[
\begin{aligned}
y_i &amp;\sim \mbox{Normal}(\mu_i, \sigma) \\
\mu_i &amp;= \beta_0 +\beta_1x_i\\
\beta_0 &amp;\sim \mbox{Normal}(0, 3) \\
\beta_1 &amp;\sim \mbox{Normal}(0, 3) \\
\sigma &amp;\sim \mbox{Normal}(0, 3) \\
\end{aligned}
\]</span></p>
<p>On a practical note, one aspect that different between Bayesian approaches and the way we have been doing modelling to this point, is that Bayesian models will usually take longer to run. Because of this, it can be useful to run the model, either within the R Markdown document or in a separate R script, and then save it with <code>saveRDS()</code>. With sensible R Markdown chunk options, the model can then be read into the R Markdown document with <code>readRDS()</code>. In this way, the model, and hence delay, is only imposed once for a given model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstanarm)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>simulated_running_data_first_model_rstanarm <span class="ot">&lt;-</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stan_lm</span>(</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    marathon_time <span class="sc">~</span> five_km_time <span class="sc">+</span> was_raining, </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> simulated_running_data,</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior =</span> <span class="cn">NULL</span>,</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">seed =</span> <span class="dv">853</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="co"># simulated_running_data_first_model_rstanarm &lt;-</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="co">#   stan_lm(</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="co">#     formula = marathon_time ~ five_km_time,</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="co">#     data = simulated_running_data,</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="co">#     prior = normal(0, 3),</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a><span class="co">#     prior_intercept = normal(0, 3),</span></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a><span class="co">#     prior_aux = normal(0, 3),</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a><span class="co">#     seed = 853</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a><span class="co">#     )</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(simulated_running_data_first_model_rstanarm,</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">file =</span> <span class="st">"simulated_running_data_first_model_rstanarm.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>simulated_running_data_first_model_rstanarm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_lm
 family:       gaussian [identity]
 formula:      marathon_time ~ five_km_time + was_raining
 observations: 100
 predictors:   3
------
               Median MAD_SD
(Intercept)    9.2    8.7   
five_km_time   7.9    0.4   
was_rainingYes 4.6    4.5   

Auxiliary parameter(s):
              Median MAD_SD
R2             0.8    0.0  
log-fit_ratio  0.0    0.0  
sigma         17.1    1.3  

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<!-- ## Tutorial -->
<!-- Let's do this in the context of the Paspaley dataset that we were introduced to in an earlier lecture. -->
<!-- Read in the data. -->
<!-- ```{r} -->
<!-- paspaley_data <- read_csv(here::here("notes/inputs/data/paspaley_cleaned_dataset.csv")) -->
<!-- head(paspaley_data) -->
<!-- ``` -->
<!-- Take a brief look: -->
<!-- ```{r} -->
<!-- skimr::skim(paspaley_data) -->

<!-- paspaley_data$keshi |> table() -->
<!-- paspaley_data$metal |> table() -->
<!-- paspaley_data$category |> table() -->
<!-- ``` -->
<!-- Clean up and remove some anonying other variables. -->
<!-- ```{r} -->
<!-- paspaley_data <-  -->
<!--   paspaley_data |>  -->
<!--   filter(metal != "Other") |>  -->
<!--   filter(category != "Other") -->
<!-- ``` -->
<!-- Run a ordinary linear regression. -->
<!-- ```{r} -->
<!-- model_1 <- lm(price ~ keshi, data = paspaley_data) -->
<!-- model_2 <- lm(price ~ metal, data = paspaley_data) -->
<!-- model_3 <- lm(price ~ category, data = paspaley_data) -->
<!-- model_4 <- lm(price ~ keshi + metal + category, data = paspaley_data) -->
<!-- ``` -->
<!-- `broom` is great to look at the models, in particular `glance` and `tidy`.  -->
<!-- ```{r} -->
<!-- summary(model_1) -->
<!-- broom::glance(model_1) -->
<!-- broom::tidy(model_1) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- broom::glance(model_4) -->
<!-- broom::tidy(model_4) -->
<!-- paspaley_data |>  -->
<!--   ggplot(aes(x = price)) + -->
<!--   geom_histogram() + -->
<!--   facet_wrap(vars(metal), scales = "free_y") -->
<!-- ``` -->
<!-- You can add the fitted variables easily too. -->
<!-- ```{r} -->
<!-- paspaley_data_with_model_4 <- broom::augment(model_4) -->
<!-- head(model_4) -->
<!-- ``` -->
</section>
<section id="logistic-regression" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">14.4</span> Logistic regression</h2>
<p>Linear regression is a nice way to come to understand better our data. But it assumes a continuous outcome variable which can take any number on the real line. We would like some way to use this same machinery when we cannot satisfy this condition. We turn to logistic and Poisson regression for binary and count outcome variables, respectively.</p>
<p>Logistic regression and its close variants are useful in a variety of settings, from elections <span class="citation" data-cites="wang2015forecasting">(<a href="references.html#ref-wang2015forecasting" role="doc-biblioref">Wang et al. 2015</a>)</span> through to horse racing <span class="citation" data-cites="chellel2018gambler boltonruth">(<a href="references.html#ref-chellel2018gambler" role="doc-biblioref">Chellel 2018</a>; <a href="references.html#ref-boltonruth" role="doc-biblioref">Bolton and Chapman 1986</a>)</span>. We use logistic regression when the dependent variable is a binary outcome, such as 0 or 1. Although the presence of a binary outcome variable may sound limiting, there are a lot of circumstances in which the outcome either naturally falls into this situation, or can be adjusted into it.</p>
<p>The reason that we use logistic regression is that we will be modelling a probability and so it will be bounded between 0 and 1. Whereas with linear regression we may end up with values outside this. This all said, logistic regression, as Daniella Witten teaches us, is just a linear model. The foundation of logistic regression is the logit function:</p>
<p><span class="math display">\[
\mbox{logit}(x) = \log\left(\frac{x}{1-x}\right),
\]</span></p>
<p>which will transpose values between 0 and 1, onto the real line. For instance, <code>logit(0.1) = -2.2</code>, <code>logit(0.5) = 0</code>, and <code>logit(0.9) = 2.2</code>.</p>
<p>We will simulate data on whether it is day or night, based on the number of cars that we can see.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>day_or_night <span class="ot">&lt;-</span> </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_of_cars =</span> <span class="fu">runif</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">min =</span> <span class="dv">0</span>, <span class="dv">100</span>),</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">noise =</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">2</span>),</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">is_night =</span> <span class="fu">if_else</span>(number_of_cars <span class="sc">+</span> noise <span class="sc">&gt;</span> <span class="dv">50</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">number_of_cars =</span> <span class="fu">round</span>(number_of_cars)) <span class="sc">|&gt;</span> </span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>noise)</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>day_or_night</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,000 × 2
   number_of_cars is_night
            &lt;dbl&gt;    &lt;dbl&gt;
 1             36        0
 2             12        0
 3             48        0
 4             32        0
 5              4        0
 6             40        0
 7             13        0
 8             24        0
 9             16        0
10             19        0
# … with 990 more rows</code></pre>
</div>
</div>
<p>As with linear regression, logistic regression with can use <code>glm()</code> from base to put together a quick model and <code>summary()</code> to look at it. In this case we will try to work out whether it is day or night, based on the number of cars we can see. We are interested in estimating Equation @ref(eq:logisticexample):</p>
<p><span class="math display">\[
\mbox{Pr}(y_i=1) = \mbox{logit}^{-1}\left(\beta_0+\beta_1 x_i\right). (\#eq:logisticexample)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>day_or_night_model <span class="ot">&lt;-</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span>(is_night <span class="sc">~</span> number_of_cars,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> day_or_night,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="st">'binomial'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(day_or_night_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = is_night ~ number_of_cars, family = "binomial", 
    data = day_or_night)

Deviance Residuals: 
     Min        1Q    Median        3Q       Max  
-2.39419  -0.00002   0.00000   0.00002   2.33776  

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    -45.5353     7.3389  -6.205 5.48e-10 ***
number_of_cars   0.9121     0.1470   6.205 5.47e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1386.194  on 999  degrees of freedom
Residual deviance:   77.243  on 998  degrees of freedom
AIC: 81.243

Number of Fisher Scoring iterations: 11</code></pre>
</div>
</div>
<p>One reason that logistic regression can be a bit tricky initially, is because the coefficients take a bit of work to interpret. In particular, our estimate on likelihood of it being night is 0.91 This is the odds. So, the odds that it is night, increase by 0.91 as the number of cars that we saw increases. We can translate the result into probabilities using <code>augment()</code> from <code>broom</code> <span class="citation" data-cites="broom">(<a href="references.html#ref-broom" role="doc-biblioref">Robinson, Hayes, and Couch 2021</a>)</span> and this allows us to graph the results (<a href="#fig-dayornightprobs">Figure&nbsp;<span>14.9</span></a>)).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>day_or_night <span class="ot">&lt;-</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(day_or_night_model,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> day_or_night,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">type.predict =</span> <span class="st">"response"</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>day_or_night</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,000 × 8
   number_of_cars is_night  .fitted   .resid .std.resid     .hat .sigma  .cooksd
            &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
 1             36        0 3.06e- 6 -2.47e-3   -2.47e-3 1.30e- 5  0.278 1.98e-11
 2             12        0 2.22e-16 -2.11e-8   -2.11e-8 6.91e-15  0.278 7.67e-31
 3             48        0 1.48e- 1 -5.65e-1   -5.71e-1 2.04e- 2  0.278 1.84e- 3
 4             32        0 7.95e- 8 -3.99e-4   -3.99e-4 5.57e- 7  0.278 2.21e-14
 5              4        0 2.22e-16 -2.11e-8   -2.11e-8 1.01e-14  0.278 1.12e-30
 6             40        0 1.17e- 4 -1.53e-2   -1.53e-2 2.58e- 4  0.278 1.51e- 8
 7             13        0 2.22e-16 -2.11e-8   -2.11e-8 6.55e-15  0.278 7.27e-31
 8             24        0 5.39e-11 -1.04e-5   -1.04e-5 7.85e-10  0.278 2.11e-20
 9             16        0 2.22e-16 -2.11e-8   -2.11e-8 5.53e-15  0.278 6.14e-31
10             19        0 5.63e-13 -1.06e-6   -1.06e-6 1.17e-11  0.278 3.29e-24
# … with 990 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>day_or_night <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">is_night =</span> <span class="fu">factor</span>(is_night)) <span class="sc">|&gt;</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> number_of_cars,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> .fitted,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> is_night)) <span class="sc">+</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.01</span>, <span class="at">height =</span> <span class="fl">0.01</span>) <span class="sc">+</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Number of cars that were seen"</span>,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Estimated probability it is night"</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Was actually night"</span>) <span class="sc">+</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-dayornightprobs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/fig-dayornightprobs-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 14.9: Logistic regression probability results with simulated data of whether it is day or night based on the number of cars that are around</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We can use <code>tidymodels</code> to run this if we wanted. In order to do that, we first need to change the class of our dependent variable into a factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>day_or_night <span class="ot">&lt;-</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  day_or_night <span class="sc">|&gt;</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">is_night =</span> <span class="fu">as_factor</span>(is_night))</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>day_or_night_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(day_or_night, <span class="at">prop =</span> <span class="fl">0.80</span>)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>day_or_night_train <span class="ot">&lt;-</span> <span class="fu">training</span>(day_or_night_split)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>day_or_night_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(day_or_night_split)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>day_or_night_tidymodels <span class="ot">&lt;-</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">logistic_reg</span>(<span class="at">mode =</span> <span class="st">"classification"</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(is_night <span class="sc">~</span> number_of_cars,</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> day_or_night_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>day_or_night_tidymodels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object

Fit time:  4ms 

Call:  stats::glm(formula = is_night ~ number_of_cars, family = stats::binomial, 
    data = data)

Coefficients:
   (Intercept)  number_of_cars  
      -44.4817          0.8937  

Degrees of Freedom: 799 Total (i.e. Null);  798 Residual
Null Deviance:      1109 
Residual Deviance: 62.5     AIC: 66.5</code></pre>
</div>
</div>
<p>As before, we can make a graph of the actual results compared with our estimates. But one nice aspect of this is that we could use our test dataset to more thoroughly evaluate our model’s forecasting ability, for instance through a confusion matrix. We find that the model does well on the held-out dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>day_or_night_tidymodels <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(<span class="at">new_data =</span> day_or_night_test) <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(day_or_night_test) <span class="sc">|&gt;</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">conf_mat</span>(<span class="at">truth =</span> is_night, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Truth
Prediction   0   1
         0  95   0
         1   3 102</code></pre>
</div>
</div>
<p>Finally, we might be interested in inference, and so want to build a Bayesian model using <code>rstanarm</code>. Again, we will more fully specify our model:</p>
<p>Finally, we can build a Bayesian model and estimate it with <code>rstanarm</code>.</p>
<p><span class="math display">\[
\begin{aligned}
\mbox{Pr}(y_i=1) &amp; = \mbox{logit}^{-1}\left(\beta_0+\beta_1 x_i\right)\\
\beta_0 &amp; \sim \mbox{Normal}(0, 3)\\
\beta_1 &amp; \sim \mbox{Normal}(0, 3)
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>day_or_night_rstanarm <span class="ot">&lt;-</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stan_glm</span>(</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>    is_night <span class="sc">~</span> number_of_cars,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> day_or_night,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior =</span> <span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">3</span>),</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior_intercept =</span> <span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">3</span>),</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">seed =</span> <span class="dv">853</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(day_or_night_rstanarm,</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">file =</span> <span class="st">"day_or_night_rstanarm.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>day_or_night_rstanarm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       binomial [logit]
 formula:      is_night ~ number_of_cars
 observations: 1000
 predictors:   2
------
               Median MAD_SD
(Intercept)    -47.3    8.0 
number_of_cars   0.9    0.2 

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
</section>
<section id="poisson-regression" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="poisson-regression"><span class="header-section-number">14.5</span> Poisson regression</h2>
<p>When we have count data, we should initially think to use Poisson distribution. The Poisson distribution has the interesting feature that the mean is also the variance, and so as the mean increases, so does the variance. As such, the Poisson distribution is governed by the parameter, <span class="math inline">\(\lambda\)</span> and it distributes probabilities over the non-negative integers. The Poisson distribution is <span class="citation" data-cites="pitman">(<a href="references.html#ref-pitman" role="doc-biblioref">Pitman 1993, 121</a>)</span>:</p>
<p><span class="math display">\[P_{\lambda}(k) = e^{-\lambda}\mu^k/k!\mbox{, for }k=0,1,2,...\]</span></p>
<p>We can simulate <span class="math inline">\(n=20\)</span> draws from the Poisson distribution with <code>rpois()</code>, where <span class="math inline">\(\lambda\)</span> is both the mean and the variance. The <span class="math inline">\(\lambda\)</span> parameter governs the shape of the distribution (<span class="quarto-unresolved-ref">?fig-poissondistributiontakingshape</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpois</span>(<span class="at">n =</span> <span class="dv">20</span>, <span class="at">lambda =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 5 5 4 5 2 1 4 5 4 6 2 3 4 4 6 5 1 3 5</code></pre>
</div>
</div>
<div class="cell" data-fig.label="poissondistributiontakingshape">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>number_of_each <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">lambda =</span> <span class="fu">c</span>(</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">0</span>, number_of_each),</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span>, number_of_each),</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">2</span>, number_of_each),</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">4</span>, number_of_each),</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">7</span>, number_of_each),</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">10</span>, number_of_each),</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">15</span>, number_of_each),</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">50</span>, number_of_each),</span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">100</span>, number_of_each)</span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">draw =</span> <span class="fu">c</span>(</span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rpois</span>(<span class="at">n =</span> number_of_each, <span class="at">lambda =</span> <span class="dv">0</span>),</span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rpois</span>(<span class="at">n =</span> number_of_each, <span class="at">lambda =</span> <span class="dv">1</span>),</span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rpois</span>(<span class="at">n =</span> number_of_each, <span class="at">lambda =</span> <span class="dv">2</span>),</span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rpois</span>(<span class="at">n =</span> number_of_each, <span class="at">lambda =</span> <span class="dv">4</span>),</span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rpois</span>(<span class="at">n =</span> number_of_each, <span class="at">lambda =</span> <span class="dv">7</span>),</span>
<span id="cb60-23"><a href="#cb60-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rpois</span>(<span class="at">n =</span> number_of_each, <span class="at">lambda =</span> <span class="dv">10</span>),</span>
<span id="cb60-24"><a href="#cb60-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rpois</span>(<span class="at">n =</span> number_of_each, <span class="at">lambda =</span> <span class="dv">15</span>),</span>
<span id="cb60-25"><a href="#cb60-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rpois</span>(<span class="at">n =</span> number_of_each, <span class="at">lambda =</span> <span class="dv">50</span>),</span>
<span id="cb60-26"><a href="#cb60-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rpois</span>(<span class="at">n =</span> number_of_each, <span class="at">lambda =</span> <span class="dv">100</span>)</span>
<span id="cb60-27"><a href="#cb60-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb60-28"><a href="#cb60-28" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb60-29"><a href="#cb60-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> draw)) <span class="sc">+</span></span>
<span id="cb60-30"><a href="#cb60-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb60-31"><a href="#cb60-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(lambda),</span>
<span id="cb60-32"><a href="#cb60-32" aria-hidden="true" tabindex="-1"></a>             <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb60-33"><a href="#cb60-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb60-34"><a href="#cb60-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Integer'</span>,</span>
<span id="cb60-35"><a href="#cb60-35" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">'Density'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="14-ijalm_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">The Poisson distribution is governed by the value of the mean, which is the same as its variance</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>For instance, if we look at the number of A+ grades that are awarded in each university course in a given term then for each course we would have a count.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>count_of_A_plus <span class="ot">&lt;-</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Thanks to Chris DuBois: https://stackoverflow.com/a/1439843</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">department =</span> <span class="fu">c</span>(<span class="fu">rep.int</span>(<span class="st">"1"</span>, <span class="dv">26</span>), <span class="fu">rep.int</span>(<span class="st">"2"</span>, <span class="dv">26</span>), <span class="fu">rep.int</span>(<span class="st">"3"</span>, <span class="dv">26</span>)),</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">course =</span> <span class="fu">c</span>(<span class="fu">paste0</span>(<span class="st">"DEP_1_"</span>, letters), <span class="fu">paste0</span>(<span class="st">"DEP_2_"</span>, letters), <span class="fu">paste0</span>(<span class="st">"DEP_3_"</span>, letters)),</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_of_A_plus =</span> <span class="fu">c</span>(</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>),</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">26</span>,</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>),</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">26</span>,</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>),</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">26</span>,</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>count_of_A_plus</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 78 × 3
   department course  number_of_A_plus
   &lt;chr&gt;      &lt;chr&gt;              &lt;int&gt;
 1 1          DEP_1_a                9
 2 1          DEP_1_b               10
 3 1          DEP_1_c                1
 4 1          DEP_1_d                5
 5 1          DEP_1_e                2
 6 1          DEP_1_f                4
 7 1          DEP_1_g                3
 8 1          DEP_1_h                3
 9 1          DEP_1_i                1
10 1          DEP_1_j                3
# … with 68 more rows</code></pre>
</div>
</div>
<p>Our simulated dataset has the number of A+ grades awarded by courses, which are structured within departments. We can use <code>glm()</code> and <code>summary()</code> from base to quickly get a sense of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>grades_model_base <span class="ot">&lt;-</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span>(number_of_A_plus <span class="sc">~</span> department, </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> count_of_A_plus, </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="st">'poisson'</span>)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grades_model_base)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = number_of_A_plus ~ department, family = "poisson", 
    data = count_of_A_plus)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-6.739  -1.210  -0.171   1.424   3.952  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.44238    0.09535  15.128   &lt;2e-16 ***
department2  1.85345    0.10254  18.075   &lt;2e-16 ***
department3  1.00663    0.11141   9.035   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 952.12  on 77  degrees of freedom
Residual deviance: 450.08  on 75  degrees of freedom
AIC: 768.21

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>The interpretation of the coefficient on ‘department2’ is that it is the log of the expected difference between departments. So we expect <span class="math inline">\(\exp(1.85345) \approx 6.3\)</span> and <span class="math inline">\(\exp(1.00663) \approx 2.7\)</span> additional A+ grades in departments 2 and 3, compared with department 1.</p>
<p>We can use <code>tidymodels</code> to estimate Poisson regression models with <code>poissonreg</code> <span class="citation" data-cites="poissonreg">(<a href="references.html#ref-poissonreg" role="doc-biblioref">Kuhn 2021</a>)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(poissonreg)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">853</span>)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>count_of_A_plus_split <span class="ot">&lt;-</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  rsample<span class="sc">::</span><span class="fu">initial_split</span>(count_of_A_plus, <span class="at">prop =</span> <span class="fl">0.80</span>)</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>count_of_A_plus_train <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">training</span>(count_of_A_plus_split)</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>count_of_A_plus_test <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">testing</span>(count_of_A_plus_split)</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>a_plus_model_tidymodels <span class="ot">&lt;-</span></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">poisson_reg</span>(<span class="at">mode =</span> <span class="st">"regression"</span>) <span class="sc">|&gt;</span></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(number_of_A_plus <span class="sc">~</span> department,</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> count_of_A_plus_train)</span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>a_plus_model_tidymodels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object

Fit time:  2ms 

Call:  stats::glm(formula = number_of_A_plus ~ department, family = stats::poisson, 
    data = data)

Coefficients:
(Intercept)  department2  department3  
      1.470        1.925        1.011  

Degrees of Freedom: 61 Total (i.e. Null);  59 Residual
Null Deviance:      758 
Residual Deviance: 276.8    AIC: 534.8</code></pre>
</div>
</div>
<p>And finally, we can build a Bayesian model and estimate it with <code>rstanarm</code>. We put a tight prior on the coefficients because of the propensity for the Poisson distribution to expand them substantially.</p>
<p><span class="math display">\[
\begin{aligned}
y_i &amp;\sim \mbox{Poisson}(\lambda_i)\\
\log(\lambda_i) &amp; = \beta_0 + \beta_1 x_1 + \beta_2 x_2\\
\beta_0 &amp; \sim \mbox{Normal}(0, 0.5)\\
\beta_1 &amp; \sim \mbox{Normal}(0, 0.5)\\
\beta_2 &amp; \sim \mbox{Normal}(0, 0.5)
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>count_of_A_plus_rstanarm <span class="ot">&lt;-</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stan_glm</span>(</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>    number_of_A_plus <span class="sc">~</span> department,</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> count_of_A_plus,</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>),</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior =</span> <span class="fu">normal</span>(<span class="dv">0</span>, <span class="fl">0.5</span>),</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">prior_intercept =</span> <span class="fu">normal</span>(<span class="dv">0</span>, <span class="fl">0.5</span>),</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">seed =</span> <span class="dv">853</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(count_of_A_plus_rstanarm,</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">file =</span> <span class="st">"count_of_A_plus_rstanarm.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>count_of_A_plus_rstanarm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       poisson [log]
 formula:      number_of_A_plus ~ department
 observations: 78
 predictors:   3
------
            Median MAD_SD
(Intercept) 1.5    0.1   
department2 1.8    0.1   
department3 0.9    0.1   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<!-- ## Proportional hazards -->
<!-- Could do like how long someone has to wait for something? -->
</section>
<section id="exercises-and-tutorial" class="level2" data-number="14.6">
<h2 data-number="14.6" class="anchored" data-anchor-id="exercises-and-tutorial"><span class="header-section-number">14.6</span> Exercises and tutorial</h2>
<section id="exercises" class="level3" data-number="14.6.1">
<h3 data-number="14.6.1" class="anchored" data-anchor-id="exercises"><span class="header-section-number">14.6.1</span> Exercises</h3>
<ol type="1">
<li><em>(Plan)</em> Consider the following scenario: <strong>TBD</strong>. Please sketch out what that dataset could look like and then sketch a graph that you could build to show all observations.</li>
<li><em>(Simulate)</em> Please further consider the scenario described and simulate the situation with every variable independent of each other.</li>
<li><em>(Acquire)</em> Please describe three possible sources of such a dataset.</li>
<li><em>(Explore)</em> Please use <code>ggplot2</code> to build the graph that you sketched.</li>
<li><em>(Communicate)</em> Please write two paragraphs about what you did.</li>
<li>Please write a linear relationship between some response variable, Y, and some predictor, X. What is the intercept term? What is the slope term? What would adding a hat to these indicate?</li>
<li>What is the least squares criterion? Similarly, what is RSS and what are we trying to do when we run least squares regression?</li>
<li>What is statistical bias?</li>
<li>If there were three variables: Snow, Temperature, and Wind, please write R code that would fit a simple linear regression to explain Snow as a function of Temperature and Wind. What do you think about another explanatory variable - daily stock market returns - to your model?</li>
<li>According to <span class="citation" data-cites="greenland2016statistical">Greenland et al. (<a href="references.html#ref-greenland2016statistical" role="doc-biblioref">2016</a>)</span>, p-values test (pick one)?
<ol type="a">
<li>All the assumptions about how the data were generated (the entire model), not just the targeted hypothesis it is supposed to test (such as a null hypothesis).</li>
<li>Whether the hypothesis targeted for testing is true or not.</li>
<li>A dichotomy whereby results can be declared ‘statistically significant’.</li>
</ol></li>
<li>According to <span class="citation" data-cites="greenland2016statistical">Greenland et al. (<a href="references.html#ref-greenland2016statistical" role="doc-biblioref">2016</a>)</span>, a p-value may be small because (select all)?
<ol type="a">
<li>The targeted hypothesis is false.</li>
<li>The study protocols were violated.</li>
<li>It was selected for presentation based on its small size.</li>
</ol></li>
<li>According to <span class="citation" data-cites="obermeyer2019dissecting">Obermeyer et al. (<a href="references.html#ref-obermeyer2019dissecting" role="doc-biblioref">2019</a>)</span>, why does racial bias occur in an algorithm used to guide health decisions in the US (pick one)?
<ol type="a">
<li>The algorithm uses health costs as a proxy for health needs.</li>
<li>The algorithm was trained on Reddit data.</li>
</ol></li>
<li>When should we use logistic regression (pick one)?
<ol type="a">
<li>Continuous dependent variable.</li>
<li>Binary dependent variable.</li>
<li>Count dependent variable.</li>
</ol></li>
<li>We are interested in studying how voting intentions in the recent US presidential election vary by an individual’s income. We set up a logistic regression model to study this relationship. In this study, one possible dependent variable would be (pick one)?
<ol type="a">
<li>Whether the respondent is a US citizen (yes/no)</li>
<li>The respondent’s personal income (high/low)</li>
<li>Whether the respondent is going to vote for Trump (yes/no)</li>
<li>Who the respondent voted for in 2016 (Trump/Clinton)</li>
</ol></li>
<li>We are interested in studying how voting intentions in the recent US presidential election vary by an individual’s income. We set up a logistic regression model to study this relationship. In this study, one possible dependent variable would be (pick one)?
<ol type="a">
<li>The race of the respondent (white/not white)</li>
<li>The respondent’s marital status (married/not)</li>
<li>Whether the respondent is registered to vote (yes/no)</li>
<li>Whether the respondent is going to vote for Biden (yes/no)</li>
</ol></li>
<li>Please explain what a p-value is, using only the term itself (i.e.&nbsp;‘p-value’) and words that are amongst the 1,000 most common in the English language according to the XKCD Simple Writer - https://xkcd.com/simplewriter/. (Please write one or two paragraphs.)</li>
<li>The mean of a Poisson distribution is equal to its?
<ol type="a">
<li>Median.</li>
<li>Standard deviation.</li>
<li>Variance.</li>
</ol></li>
<li>What is power (in a statistical context)?</li>
<li>According to <span class="citation" data-cites="citemcelreath">McElreath (<a href="references.html#ref-citemcelreath" role="doc-biblioref">2020, 162</a>)</span> ‘Regression will not sort it out. Regression is indeed an oracle, but a cruel one. It speaks in riddles and delights in punishing us for…’ (please select one answer)?
<ol type="a">
<li>overcomplicating models.</li>
<li>asking bad questions.</li>
<li>using bad data.</li>
</ol></li>
<li>Is a model that fits the small or large world more important to you, and why?</li>
</ol>
</section>
<section id="tutorial" class="level3" data-number="14.6.2">
<h3 data-number="14.6.2" class="anchored" data-anchor-id="tutorial"><span class="header-section-number">14.6.2</span> Tutorial</h3>
<p>Simulate some data that are similar to those discussed by <span class="citation" data-cites="gould2013median">Gould (<a href="references.html#ref-gould2013median" role="doc-biblioref">2013</a>)</span>. Then build a regression model. Discuss your results</p>
<!-- ### Paper -->
<!-- At about this point, Paper Four (Appendix \@ref(paper-four)) would be appropriate. -->


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-citemodelsummary" class="csl-entry" role="doc-biblioentry">
Arel-Bundock, Vincent. 2021. <em>Modelsummary: Summary Tables and Plots for Statistical Models and Data: Beautiful, Customizable, and Publication-Ready</em>. <a href="https://CRAN.R-project.org/package=modelsummary">https://CRAN.R-project.org/package=modelsummary</a>.
</div>
<div id="ref-boltonruth" class="csl-entry" role="doc-biblioentry">
Bolton, Ruth, and Randall Chapman. 1986. <span>“Searching for Positive Returns at the Track.”</span> <em>Management Science</em> 32 (August): 1040–60. <a href="https://doi.org/10.1287/mnsc.32.8.1040">https://doi.org/10.1287/mnsc.32.8.1040</a>.
</div>
<div id="ref-chellel2018gambler" class="csl-entry" role="doc-biblioentry">
Chellel, Kit. 2018. <span>“The Gambler Who Cracked the Horse-Racing Code.”</span> <em>Bloomberg Businessweek (May 2018). Featured in Bloomberg Businessweek, May</em> 14.
</div>
<div id="ref-coxtalks" class="csl-entry" role="doc-biblioentry">
Cox, David. 2018. <span>“In Gentle Praise of Significance Tests.”</span> <em>YouTube</em>, October. <a href="https://youtu.be/txLj\%5FP9UlCQ">https://youtu.be/txLj\%5FP9UlCQ</a>.
</div>
<div id="ref-cox1987parameter" class="csl-entry" role="doc-biblioentry">
Cox, David Roxbee, and Nancy Reid. 1987. <span>“Parameter Orthogonality and Approximate Conditional Inference.”</span> <em>Journal of the Royal Statistical Society: Series B (Methodological)</em> 49 (1): 1–18.
</div>
<div id="ref-cramer2002origins" class="csl-entry" role="doc-biblioentry">
Cramer, Jan Salomon. 2002. <span>“The Origins of Logistic Regression.”</span>
</div>
<div id="ref-gelmanandhill" class="csl-entry" role="doc-biblioentry">
Gelman, Andrew, and Jennifer Hill. 2007. <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>.
</div>
<div id="ref-citerstanarm" class="csl-entry" role="doc-biblioentry">
Goodrich, Ben, Jonah Gabry, Imad Ali, and Sam Brilleman. 2020. <span>“Rstanarm: <span>Bayesian</span> Applied Regression Modeling via <span>Stan</span>.”</span> <a href="https://mc-stan.org/rstanarm">https://mc-stan.org/rstanarm</a>.
</div>
<div id="ref-gould2013median" class="csl-entry" role="doc-biblioentry">
Gould, Stephen Jay. 2013. <span>“The Median Isn’t the Message.”</span> <em>AMA Journal of Ethics</em> 15 (1): 77–81.
</div>
<div id="ref-greenland2016statistical" class="csl-entry" role="doc-biblioentry">
Greenland, Sander, Stephen J Senn, Kenneth J Rothman, John B Carlin, Charles Poole, Steven N Goodman, and Douglas G Altman. 2016. <span>“Statistical Tests, p Values, Confidence Intervals, and Power: A Guide to Misinterpretations.”</span> <em>European Journal of Epidemiology</em> 31 (4): 337–50.
</div>
<div id="ref-hastie1990generalized" class="csl-entry" role="doc-biblioentry">
Hastie, Trevor J, and Robert J Tibshirani. 1990. <em>Generalized Additive Models</em>. Vol. 43. CRC press.
</div>
<div id="ref-ioannidis2005most" class="csl-entry" role="doc-biblioentry">
Ioannidis, John PA. 2005. <span>“Why Most Published Research Findings Are False.”</span> <em>PLoS Medicine</em> 2 (8): e124.
</div>
<div id="ref-islr" class="csl-entry" role="doc-biblioentry">
James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2017. <em><span class="nocase">An Introduction to Statistical Learning with Applications in R</span></em>.
</div>
<div id="ref-poissonreg" class="csl-entry" role="doc-biblioentry">
Kuhn, Max. 2021. <em>Poissonreg: Model Wrappers for Poisson Regression</em>. <a href="https://CRAN.R-project.org/package=poissonreg">https://CRAN.R-project.org/package=poissonreg</a>.
</div>
<div id="ref-citeTidymodels" class="csl-entry" role="doc-biblioentry">
Kuhn, Max, and Hadley Wickham. 2020. <em>Tidymodels: A Collection of Packages for Modeling and Machine Learning Using Tidyverse Principles</em>. <a href="https://www.tidymodels.org">https://www.tidymodels.org</a>.
</div>
<div id="ref-citemcelreath" class="csl-entry" role="doc-biblioentry">
McElreath, Richard. 2020. <em><span class="nocase">Statistical Rethinking: A Bayesian Course with Examples in R and Stan</span></em>. CRC Press.
</div>
<div id="ref-nelder1972generalized" class="csl-entry" role="doc-biblioentry">
Nelder, John Ashworth, and Robert WM Wedderburn. 1972. <span>“Generalized Linear Models.”</span> <em>Journal of the Royal Statistical Society: Series A (General)</em> 135 (3): 370–84.
</div>
<div id="ref-obermeyer2019dissecting" class="csl-entry" role="doc-biblioentry">
Obermeyer, Ziad, Brian Powers, Christine Vogeli, and Sendhil Mullainathan. 2019. <span>“Dissecting Racial Bias in an Algorithm Used to Manage the Health of Populations.”</span> <em>Science</em> 366 (6464): 447–53.
</div>
<div id="ref-pitman" class="csl-entry" role="doc-biblioentry">
Pitman, Jim. 1993. <em>Probability</em>. Springer.
</div>
<div id="ref-reid2003asymptotics" class="csl-entry" role="doc-biblioentry">
Reid, Nancy. 2003. <span>“Asymptotics and the Theory of Inference.”</span> <em>The Annals of Statistics</em> 31 (6): 1695–2095.
</div>
<div id="ref-broom" class="csl-entry" role="doc-biblioentry">
Robinson, David, Alex Hayes, and Simon Couch. 2021. <em>Broom: Convert Statistical Objects into Tidy Tibbles</em>. <a href="https://CRAN.R-project.org/package=broom">https://CRAN.R-project.org/package=broom</a>.
</div>
<div id="ref-Staicu2017" class="csl-entry" role="doc-biblioentry">
Staicu, Ana-Maria. 2017. <span>“Interview with Nancy Reid.”</span> <em>International Statistical Review</em> 85 (3): 381–403. <a href="https://doi.org/10.1111/insr.12237">https://doi.org/10.1111/insr.12237</a>.
</div>
<div id="ref-stigler" class="csl-entry" role="doc-biblioentry">
Stigler, Stephen. 1986. <em>The History of Statistics</em>. Harvard University Press.
</div>
<div id="ref-varin2011overview" class="csl-entry" role="doc-biblioentry">
Varin, Cristiano, Nancy Reid, and David Firth. 2011. <span>“An Overview of Composite Likelihood Methods.”</span> <em>Statistica Sinica</em>, 5–42.
</div>
<div id="ref-wang2015forecasting" class="csl-entry" role="doc-biblioentry">
Wang, Wei, David Rothschild, Sharad Goel, and Andrew Gelman. 2015. <span>“Forecasting Elections with Non-Representative Polls.”</span> <em>International Journal of Forecasting</em> 31 (3): 980–91.
</div>
<div id="ref-wasserman" class="csl-entry" role="doc-biblioentry">
Wasserman, Larry. 2005. <em>All of Statistics</em>. Springer.
</div>
<div id="ref-tidyverse" class="csl-entry" role="doc-biblioentry">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al. 2019. <span>“Welcome to the <span class="nocase">tidyverse</span>.”</span> <em>Journal of Open Source Software</em> 4 (43): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
<div id="ref-wilde" class="csl-entry" role="doc-biblioentry">
Wilde, Oscar. 1891. <em>The Picture of Dorian Gray</em>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./13-eda.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Exploratory data analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./15-causality_from_obs.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Causality from observational data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>